import { Payload } from 'payload'
import { MediaMap } from './media.seeder'
import { FontMap } from './fonts.seeder'

export async function seedGlobals(payload: Payload, mediaMap: MediaMap | null, fontMap: FontMap | null) {
    console.log('🌱 Seeding globals...')

    // Seed Header
    await payload.updateGlobal({
        slug: 'header',
        data: {
            headerBackgroundColor: '#F2EBD0',
            headerTextColor: '#4a4b34',
            ownerName: 'Akanksha Rajpati',
            ownerFont: fontMap?.playfairDisplay,
            navItems: [
                { label: 'Home', link: '/', font: fontMap?.nunito },
                { label: 'About', link: '/about', font: fontMap?.nunito },
                { label: 'Blog', link: '/blog', font: fontMap?.nunito },
                { label: 'Shop', link: '/shop', font: fontMap?.nunito },
                { label: 'Watch', link: '/watch', font: fontMap?.nunito },
                { label: 'Contact', link: '/contact', font: fontMap?.nunito },
            ],
            socialLinks: [
                { platform: 'Instagram', url: 'https://instagram.com', font: fontMap?.nunito },
                { platform: 'YouTube', url: 'https://youtube.com', font: fontMap?.nunito },
                { platform: 'Pinterest', url: 'https://pinterest.com', font: fontMap?.nunito },
            ],
            navIcons: [
                { type: 'search', showIcon: true, showLabel: false, showIconOnMobile: true, showIconOnDesktop: true, label: 'Search', enabled: true },
                { type: 'link', link: '/shop', showIcon: true, showLabel: false, showIconOnMobile: false, showIconOnDesktop: true, label: 'Shop', enabled: true },
            ],
            primaryColor: '#B88078',
            secondaryColor: '#C49A48',
            backgroundColor: '#F2EBD0',
            textColor: '#4a4b34',
            mutedTextColor: '#6b6c4f',
            borderColor: '#C49A48',
        },
    })
    console.log('✅ Header seeded')

    // Seed Footer
    await payload.updateGlobal({
        slug: 'footer',
        data: {
            enabled: true,
            brandEnabled: true,
            brandName: 'Akanksha Rajpati',
            brandNameFont: fontMap?.playfairDisplay,
            brandDescription: 'A luxury lifestyle journal dedicated to the refined aesthetics of the transitional seasons. Based in England, reaching the world.',
            brandDescriptionFont: fontMap?.cormorantGaramond,
            brandNameColor: '#4a4b34',
            brandDescriptionColor: '#6b6c4f',
            discoverLinksEnabled: true,
            discoverLinksHeading: 'Discover',
            discoverLinks: [
                { label: 'Home', link: '/' },
                { label: 'About', link: '/about' },
                { label: 'Blog', link: '/blog' },
                { label: 'Shop', link: '/shop' },
            ],
            infoLinksEnabled: true,
            infoLinksHeading: 'Information',
            infoLinks: [
                { label: 'Privacy Policy', link: '/privacy' },
                { label: 'Terms of Service', link: '/terms' },
                { label: 'Contact', link: '/contact' },
            ],
            newsletterEnabled: true,
            newsletterHeading: 'Stay Inspired',
            newsletterHeadingFont: fontMap?.playfairDisplay,
            newsletterDescription: 'Join our community for exclusive content, early access, and seasonal inspirations.',
            newsletterDescriptionFont: fontMap?.cormorantGaramond,
            newsletterHeadingColor: '#4a4b34',
            newsletterDescriptionColor: '#6b6c4f',
            newsletterButtonText: 'Subscribe',
            socialLinksEnabled: true,
            socialLinks: [
                { platform: 'Instagram', url: 'https://instagram.com', showIcon: true },
                { platform: 'YouTube', url: 'https://youtube.com', showIcon: true },
                { platform: 'Pinterest', url: 'https://pinterest.com', showIcon: true },
            ],
            copyrightEnabled: true,
            copyrightText: '© 2026 Akanksha Rajpati. All rights reserved.',
            copyrightTextFont: fontMap?.nunito,
            copyrightTextColor: '#6b6c4f',
            primaryColor: '#B88078',
            secondaryColor: '#C49A48',
            backgroundColor: '#F2EBD0',
            textColor: '#4a4b34',
            mutedTextColor: '#6b6c4f',
            borderColor: '#C49A48',
        },
    })
    console.log('✅ Footer seeded')

    // Seed Join Our Inner Circle
    await payload.updateGlobal({
        slug: 'join-our-inner-circle',
        data: {
            enabled: true,
            title: 'Join Our Inner Circle',
            titleFont: fontMap?.playfairDisplay,
            titleColor: '#4a4b34',
            description: 'Subscribe to get exclusive updates, offers, and early access to new content.',
            descriptionFont: fontMap?.cormorantGaramond,
            descriptionColor: '#6b6c4f',
            buttonText: 'Subscribe Now',
            buttonFont: fontMap?.nunito,
            buttonTextColor: '#F2EBD0',
            buttonBackgroundColor: '#4a4b34',
            backgroundColor: '#F2EBD0',
            primaryColor: '#B88078',
            secondaryColor: '#C49A48',
            textColor: '#4a4b34',
            mutedTextColor: '#6b6c4f',
            borderColor: '#C49A48',
            inputBackgroundColor: '#FFFFFF',
        },
    })
    console.log('✅ Join Our Inner Circle seeded')

    // Seed Home Page
    await payload.updateGlobal({
        slug: 'home-page',
        data: {
            pageEnabled: true,
            heroEnabled: true,
            showHeroImage: true,
            heroImage: mediaMap?.heroAutumn,
            heroHeadingLine1: 'Between Summer',
            heroHeadingLine1Font: fontMap?.playfairDisplay,
            heroHeadingLine1Color: '#4a4b34',
            heroHeadingLine2: '& Autumn',
            heroHeadingLine2Font: fontMap?.playfairDisplay,
            heroHeadingLine2Color: '#B88078',
            heroDescription: 'Capturing the golden transition where warmth meets the crisp morning air, curated for the modern romantic.',
            heroDescriptionFont: fontMap?.cormorantGaramond,
            heroDescriptionColor: '#6b6c4f',
            heroButtonText: 'The Journal',
            heroButtonLink: '/blog',
            heroButtonFont: fontMap?.nunito,
            heroButtonTextColor: '#F2EBD0',
            heroButtonBgColor: '#4a4b34',
            aboutPreviewEnabled: true,
            showAboutPreviewImage: true,
            aboutPreviewImage: mediaMap?.heroAbout,
            aboutPreviewSectionLabel: 'The Creative Vision',
            aboutPreviewSectionLabelFont: fontMap?.nunito,
            aboutPreviewSectionLabelColor: '#B88078',
            aboutPreviewHeadingNormal: "Hello, I'm",
            aboutPreviewHeadingNormalFont: fontMap?.playfairDisplay,
            aboutPreviewHeadingNormalColor: '#4a4b34',
            aboutPreviewHeadingAccent: 'Akanksha',
            aboutPreviewHeadingAccentFont: fontMap?.playfairDisplay,
            aboutPreviewHeadingAccentColor: '#B88078',
            aboutPreviewTextMain: 'Welcome to my digital editorial—a dedicated space for slow living, high-end fashion, and the quiet luxury of the autumnal season.',
            aboutPreviewTextMainFont: fontMap?.cormorantGaramond,
            aboutPreviewTextMainColor: '#6b6c4f',
            aboutPreviewTextSecondary: "Based in the Cotswolds, I've spent years refining an aesthetic that honors the seasons. This platform serves as a curated guide for those who seek beauty in the mundane and elegance in the everyday.",
            aboutPreviewTextSecondaryFont: fontMap?.cormorantGaramond,
            aboutPreviewTextSecondaryColor: '#6b6c4f',
            aboutPreviewButtonText: 'Learn More About My Story',
            aboutPreviewButtonLink: '/about',
            shopPreviewEnabled: true,
            shopPreviewSectionLabel: 'The Curated Edit',
            shopPreviewSectionLabelFont: fontMap?.nunito,
            shopPreviewSectionLabelColor: '#B88078',
            shopPreviewHeadingNormal: 'Shop My',
            shopPreviewHeadingNormalFont: fontMap?.playfairDisplay,
            shopPreviewHeadingNormalColor: '#4a4b34',
            shopPreviewHeadingAccent: 'Autumn Edits',
            shopPreviewHeadingAccentFont: fontMap?.playfairDisplay,
            shopPreviewHeadingAccentColor: '#B88078',
            shopPreviewDescription: 'Handpicked pieces for your wardrobe and home.',
            shopPreviewDescriptionFont: fontMap?.cormorantGaramond,
            shopPreviewDescriptionColor: '#6b6c4f',
            shopPreviewButtonText: 'Browse Collection',
            shopPreviewButtonLink: '/shop',
            blogPreviewEnabled: true,
            blogPreviewSectionLabel: 'The Journal',
            blogPreviewSectionLabelFont: fontMap?.nunito,
            blogPreviewSectionLabelColor: '#B88078',
            blogPreviewHeadingNormal: 'Latest',
            blogPreviewHeadingNormalFont: fontMap?.playfairDisplay,
            blogPreviewHeadingNormalColor: '#4a4b34',
            blogPreviewHeadingAccent: 'Stories',
            blogPreviewHeadingAccentFont: fontMap?.playfairDisplay,
            blogPreviewHeadingAccentColor: '#B88078',
            blogPreviewButtonText: 'View All Stories',
            blogPreviewButtonLink: '/blog',
            watchPreviewEnabled: true,
            watchPreviewSectionLabel: 'The Visual Diary',
            watchPreviewSectionLabelFont: fontMap?.nunito,
            watchPreviewSectionLabelColor: '#B88078',
            watchPreviewHeadingNormal: 'Recent',
            watchPreviewHeadingNormalFont: fontMap?.playfairDisplay,
            watchPreviewHeadingNormalColor: '#4a4b34',
            watchPreviewHeadingAccent: 'Videos',
            watchPreviewHeadingAccentFont: fontMap?.playfairDisplay,
            watchPreviewHeadingAccentColor: '#B88078',
            watchPreviewDescription: 'Visual stories capturing the beauty of seasonal living, from golden-hour routines to curated travel diaries.',
            watchPreviewDescriptionFont: fontMap?.cormorantGaramond,
            watchPreviewDescriptionColor: '#6b6c4f',
            watchPreviewButtonText: 'Watch All Videos',
            watchPreviewButtonLink: '/watch',
            contactPreviewEnabled: true,
            contactPreviewSectionLabel: "Let's Connect",
            contactPreviewSectionLabelFont: fontMap?.nunito,
            contactPreviewSectionLabelColor: '#B88078',
            contactPreviewHeadingNormal: 'Get in',
            contactPreviewHeadingNormalFont: fontMap?.playfairDisplay,
            contactPreviewHeadingNormalColor: '#4a4b34',
            contactPreviewHeadingAccent: 'Touch',
            contactPreviewHeadingAccentFont: fontMap?.playfairDisplay,
            contactPreviewHeadingAccentColor: '#B88078',
            contactPreviewDescription: "Have a question, collaboration idea, or just want to say hello? I'd love to hear from you.",
            contactPreviewDescriptionFont: fontMap?.cormorantGaramond,
            contactPreviewDescriptionColor: '#6b6c4f',
            contactPreviewButtonText: 'Get in Touch',
            contactPreviewButtonLink: '/contact',
            primaryColor: '#B88078',
            secondaryColor: '#C49A48',
            backgroundColor: '#F2EBD0',
            cardBackgroundColor: '#F2EBD0',
            textColor: '#4a4b34',
            mutedTextColor: '#6b6c4f',
            borderColor: '#C49A48',
            buttonPrimaryBgColor: '#4a4b34',
            buttonPrimaryTextColor: '#F2EBD0',
        },
    })
    console.log('✅ Home Page seeded')

    // Seed About Page
    await payload.updateGlobal({
        slug: 'about-page',
        data: {
            pageEnabled: true,
            heroEnabled: true,
            showHeroImage: true,
            heroImage: mediaMap?.heroAbout,
            sectionLabel: 'The Creative Vision',
            sectionLabelFont: fontMap?.nunito,
            sectionLabelColor: '#B88078',
            headingNormal: "Hello, I'm",
            headingNormalFont: fontMap?.playfairDisplay,
            headingNormalColor: '#4a4b34',
            headingAccent: 'Akanksha Rajpati',
            headingAccentFont: fontMap?.playfairDisplay,
            headingAccentColor: '#B88078',
            introTextMain: 'A lifestyle curator, storyteller, and eternal romantic captivated by the poetry of changing seasons.',
            introTextMainFont: fontMap?.cormorantGaramond,
            introTextMainColor: '#6b6c4f',
            introTextSecondary: "Based in the heart of England's countryside, I've dedicated my life to capturing the fleeting beauty that exists between summer's warmth and autumn's embrace.",
            introTextSecondaryFont: fontMap?.cormorantGaramond,
            introTextSecondaryColor: '#6b6c4f',
            showSignatureImage: true,
            signatureImage: mediaMap?.signatureImage,
            philosophyEnabled: true,
            philosophyLabel: 'My Philosophy',
            philosophyLabelFont: fontMap?.nunito,
            philosophyLabelColor: '#B88078',
            philosophyQuote: '"Beauty lies in the details we often overlook"',
            philosophyQuoteFont: fontMap?.playfairDisplay,
            philosophyQuoteColor: '#4a4b34',
            philosophyText: "Every piece I curate, every story I tell, is rooted in the belief that luxury isn't about excess—it's about intention. It's the warmth of a handwoven throw, the scent of a perfectly blended candle, the way autumn light falls through a window.",
            philosophyTextFont: fontMap?.cormorantGaramond,
            philosophyTextColor: '#6b6c4f',
            valuesEnabled: true,
            valuesLabel: 'Core Values',
            valuesLabelFont: fontMap?.nunito,
            valuesLabelColor: '#B88078',
            valuesHeadingNormal: 'What I',
            valuesHeadingNormalFont: fontMap?.playfairDisplay,
            valuesHeadingNormalColor: '#4a4b34',
            valuesHeadingAccent: 'Stand For',
            valuesHeadingAccentFont: fontMap?.playfairDisplay,
            valuesHeadingAccentColor: '#B88078',
            values: [
                {
                    showIcon: true,
                    icon: mediaMap?.valueIcon1,
                    title: 'Intentional Living',
                    titleFont: fontMap?.playfairDisplay,
                    titleColor: '#4a4b34',
                    description: 'Embracing quality over quantity, mindfulness over haste, and purpose over impulse in every aspect of life.',
                    descriptionFont: fontMap?.cormorantGaramond,
                    descriptionColor: '#6b6c4f',
                },
                {
                    showIcon: true,
                    icon: mediaMap?.valueIcon2,
                    title: 'Seasonal Beauty',
                    titleFont: fontMap?.playfairDisplay,
                    titleColor: '#4a4b34',
                    description: 'Finding magic in the changing seasons, celebrating the unique gifts each time of year brings to our lives.',
                    descriptionFont: fontMap?.cormorantGaramond,
                    descriptionColor: '#6b6c4f',
                },
                {
                    showIcon: true,
                    icon: mediaMap?.valueIcon3,
                    title: 'Authentic Expression',
                    titleFont: fontMap?.playfairDisplay,
                    titleColor: '#4a4b34',
                    description: 'Creating from the heart, sharing genuine experiences, and building connections through honest storytelling.',
                    descriptionFont: fontMap?.cormorantGaramond,
                    descriptionColor: '#6b6c4f',
                },
            ],
            primaryColor: '#B88078',
            secondaryColor: '#C49A48',
            backgroundColor: '#F2EBD0',
            cardBackgroundColor: '#F2EBD0',
            textColor: '#4a4b34',
            mutedTextColor: '#6b6c4f',
            borderColor: '#C49A48',
        },
    })
    console.log('✅ About Page seeded')

    // Seed Blog Page
    await payload.updateGlobal({
        slug: 'blog-page',
        data: {
            pageEnabled: true,
            headerEnabled: true,
            sectionLabel: 'The Journal',
            sectionLabelFont: fontMap?.nunito,
            sectionLabelColor: '#B88078',
            headingNormal: 'Stories &',
            headingNormalFont: fontMap?.playfairDisplay,
            headingNormalColor: '#4a4b34',
            headingAccent: 'Inspirations',
            headingAccentFont: fontMap?.playfairDisplay,
            headingAccentColor: '#B88078',
            description: 'Thoughtful essays on slow living, seasonal transitions, and the art of finding beauty in everyday moments.',
            descriptionFont: fontMap?.cormorantGaramond,
            descriptionColor: '#6b6c4f',
            newsletterHeading: 'Never Miss a Story',
            newsletterHeadingFont: fontMap?.playfairDisplay,
            newsletterHeadingColor: '#4a4b34',
            newsletterText: 'Subscribe to receive our latest articles directly in your inbox.',
            newsletterTextFont: fontMap?.cormorantGaramond,
            newsletterTextColor: '#6b6c4f',
            newsletterButtonText: 'Subscribe',
            newsletterButtonTextFont: fontMap?.nunito,
            newsletterButtonTextColor: '#F2EBD0',
            shareHeading: 'Share the Inspiration',
            shareHeadingFont: fontMap?.playfairDisplay,
            shareHeadingColor: '#4a4b34',
            shareSubheading: 'Help others discover these stories',
            shareSubheadingFont: fontMap?.cormorantGaramond,
            shareSubheadingColor: '#6b6c4f',
            socialPlatforms: [
                { platform: 'Facebook', shareUrl: 'https://facebook.com/sharer/sharer.php?u={url}', showIcon: true, textFont: fontMap?.nunito },
                { platform: 'Twitter', shareUrl: 'https://twitter.com/intent/tweet?text={title}&url={url}', showIcon: true, textFont: fontMap?.nunito },
                { platform: 'Pinterest', shareUrl: 'https://pinterest.com/pin/create/button/?url={url}&description={title}', showIcon: true, textFont: fontMap?.nunito },
                { platform: 'Instagram', showIcon: true, customText: 'Share on Instagram', textFont: fontMap?.nunito },
                { platform: 'LinkedIn', shareUrl: 'https://linkedin.com/sharing/share-offsite/?url={url}', showIcon: true, textFont: fontMap?.nunito },
            ],
            primaryColor: '#B88078',
            secondaryColor: '#C49A48',
            backgroundColor: '#F2EBD0',
            cardBackgroundColor: '#F2EBD0',
            textColor: '#4a4b34',
            mutedTextColor: '#6b6c4f',
            borderColor: '#C49A48',
        },
    })
    console.log('✅ Blog Page seeded')

    // Seed Shop Page
    const shopProducts = [
        {
            name: 'The Autumn Journal — Linen Bound Hardcover',
            description: 'A beautifully crafted hardcover journal with linen binding, 240 pages of cream-colored paper, and a ribbon bookmark. Perfect for morning pages, travel notes, or creative writing.',
            price: '$48',
            category: 'Books',
            image: mediaMap?.journalProduct,
            badge: 'Bestseller',
            badgeColor: '#B88078',
            link: '/shop/autumn-journal',
            publishedAt: new Date('2026-03-10').toISOString(),
        },
        {
            name: 'Digital Capsule Wardrobe Planner',
            description: 'An interactive digital planner for Notion and GoodNotes. Includes seasonal wardrobe audits, outfit grids, packing lists, and style analytics. Instant download.',
            price: '$24',
            category: 'Digital',
            image: mediaMap?.digitalPlanner,
            badge: 'Digital Download',
            badgeColor: '#4a4b34',
            link: '/shop/capsule-planner',
            isDigital: true,
            publishedAt: new Date('2026-03-01').toISOString(),
        },
        {
            name: 'The Seasonal Living Bundle — Digital Guide',
            description: 'A comprehensive digital guide to seasonal living, including recipes, decor guides, wellness rituals, and journaling prompts for autumn. 85 pages of inspiration.',
            price: '$36',
            salePrice: '$24',
            category: 'Digital',
            image: mediaMap?.digitalPlanner,
            badge: 'Sale',
            badgeColor: '#C49A48',
            link: '/shop/seasonal-living-bundle',
            isDigital: true,
            publishedAt: new Date('2026-02-20').toISOString(),
        },
        {
            name: 'Signature Scent Collection — Soy Candle Set',
            description: 'Hand-poured soy candles in amber glass jars. Set of three seasonal scents: Autumn Leaves, Vanilla & Clove, and Cedar & Sage. Each burns for 45+ hours.',
            price: '$72',
            category: 'Home Decor',
            image: mediaMap?.candleProduct,
            badge: 'Limited Edition',
            badgeColor: '#B88078',
            link: '/shop/candle-set',
            publishedAt: new Date('2026-02-10').toISOString(),
        },
        {
            name: 'Botanical Bookmark Set — Hand-Pressed Flowers',
            description: 'Set of six handcrafted bookmarks featuring pressed autumn flowers and botanicals. Each bookmark is unique, sealed in biodegradable laminate. A perfect gift for readers.',
            price: '$18',
            category: 'Stationery',
            image: mediaMap?.bookmarkSet,
            link: '/shop/bookmark-set',
            publishedAt: new Date('2026-01-28').toISOString(),
        },
        {
            name: 'Autumn Leaves Art Print — A3 Archival Giclée',
            description: 'An archival-quality giclée print featuring original photography of autumn leaves in golden light. Printed on 240gsm museum-grade paper. Unframed.',
            price: '$55',
            category: 'Home Decor',
            image: mediaMap?.wallArt,
            badge: 'New',
            badgeColor: '#4a4b34',
            link: '/shop/autumn-print',
            publishedAt: new Date('2026-01-15').toISOString(),
        },
        {
            name: 'The Slow Living Starter Kit — Journal & Planner Bundle',
            description: 'Everything you need to begin your slow living journey: the Linen Bound Journal, Digital Capsule Planner, and Seasonal Living Guide. Save 20% with the bundle.',
            price: '$86',
            salePrice: '$68',
            category: 'Books',
            image: mediaMap?.journalProduct,
            badge: 'Bundle & Save',
            badgeColor: '#C49A48',
            link: '/shop/slow-living-bundle',
            publishedAt: new Date('2025-12-15').toISOString(),
        },
        {
            name: 'Handcrafted Stationery Set — Letter Writing Kit',
            description: 'A luxurious letter-writing set featuring 10 sheets of cotton paper, 5 envelopes, a wax seal kit, and a fountain pen-friendly ink. Presented in a linen storage box.',
            price: '$42',
            category: 'Stationery',
            image: mediaMap?.stationerySet,
            link: '/shop/stationery-set',
            publishedAt: new Date('2025-11-20').toISOString(),
        },
    ]

    await payload.updateGlobal({
        slug: 'shop-page',
        data: {
            pageEnabled: true,
            heroEnabled: true,
            heroBackgroundColor: '#F2EBD0',
            showHeroImage: true,
            heroImage: mediaMap?.heroAutumn,
            heroImageOpacity: 10,
            heroSectionLabel: 'Autumn Collection 2026',
            heroSectionLabelFont: fontMap?.nunito,
            heroSectionLabelColor: '#B88078',
            heroHeading: 'Curated Living: Books & Digital',
            heroHeadingFont: fontMap?.playfairDisplay,
            heroHeadingColor: '#4a4b34',
            heroDescription: 'A collection designed for the slow-living enthusiast. Elevate your coffee table and digital workspace with our signature earth-toned aesthetics.',
            heroDescriptionFont: fontMap?.cormorantGaramond,
            heroDescriptionColor: '#6b6c4f',
            heroPrimaryButtonEnabled: true,
            heroPrimaryButtonText: 'Browse Collection',
            heroPrimaryButtonLink: '#shop',
            heroPrimaryButtonFont: fontMap?.nunito,
            heroPrimaryButtonBgColor: '#4a4b34',
            heroPrimaryButtonTextColor: '#F2EBD0',
            heroSecondaryButtonEnabled: true,
            heroSecondaryButtonText: 'Digital Assets',
            heroSecondaryButtonLink: '#digital',
            heroSecondaryButtonFont: fontMap?.nunito,
            heroSecondaryButtonBorderColor: '#4a4b34',
            heroSecondaryButtonTextColor: '#4a4b34',
            filterBarEnabled: true,
            categories: [
                { name: 'All', slug: 'all' },
                { name: 'Books', slug: 'books' },
                { name: 'Digital', slug: 'digital' },
                { name: 'Home Decor', slug: 'home-decor' },
                { name: 'Stationery', slug: 'stationery' },
            ],
            categoryFont: fontMap?.nunito,
            categoryActiveColor: '#4a4b34',
            categoryInactiveColor: '#6b6c4f',
            showSortDropdown: true,
            sortOptions: [
                { label: 'Newest', value: 'newest' },
                { label: 'Price: Low to High', value: 'price-asc' },
                { label: 'Price: High to Low', value: 'price-desc' },
            ],
            productsEnabled: true,
            productsGridColumns: '3',
            productCardHeight: 450,
            showQuickViewButton: true,
            quickViewButtonText: 'Quick View',
            products: shopProducts as any,
            productNameFont: fontMap?.playfairDisplay,
            productNameColor: '#4a4b34',
            productPriceFont: fontMap?.cormorantGaramond,
            productPriceColor: '#B88078',
            productCategoryColor: '#6b6c4f',
            bannerEnabled: true,
            bannerBackgroundColor: '#F2EBD0',
            bannerSectionLabel: 'Limited Edition',
            bannerSectionLabelFont: fontMap?.nunito,
            bannerSectionLabelColor: '#B88078',
            bannerHeading: 'The Autumn Journal Collection',
            bannerHeadingFont: fontMap?.playfairDisplay,
            bannerHeadingColor: '#4a4b34',
            bannerDescription: 'A carefully curated bundle featuring our bestselling journal, digital planner, and signature candle. Available while supplies last.',
            bannerDescriptionFont: fontMap?.cormorantGaramond,
            bannerDescriptionColor: '#6b6c4f',
            bannerButtonText: 'Shop the Bundle — $180',
            bannerButtonLink: '/shop',
            bannerButtonFont: fontMap?.nunito,
            bannerButtonBgColor: '#4a4b34',
            bannerButtonTextColor: '#F2EBD0',
            pageBackgroundColor: '#F2EBD0',
            primaryAccentColor: '#B88078',
            secondaryAccentColor: '#C49A48',
            borderColor: '#C49A48',
            cardBackgroundColor: '#F2EBD0',
            currencySymbol: '$',
            currencyPosition: 'before',
            showAddToCartButton: true,
            addToCartButtonText: 'Add to Cart',
            showSaleBadge: true,
            saleBadgeText: 'Sale',
            saleBadgeColor: '#C49A48',
            emptyStateHeading: 'No products found',
            emptyStateDescription: 'Try adjusting your filters or check back later for new arrivals.',
        },
    })
    console.log('✅ Shop Page seeded (8 products)')

    // Seed Watch Page
    const galleryVideos = [
        {
            title: 'A Week in the Cotswolds — Autumn Travel Vlog',
            slug: 'cotswolds-travel-vlog',
            thumbnail: mediaMap?.videoThumbnail1,
            videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
            duration: '24:15',
            category: 'travel',
            views: 85600,
            publishedAt: new Date('2026-02-10').toISOString(),
        },
        {
            title: 'Vintage Shopping in Paris — Street Style Tour',
            slug: 'paris-vintage-shopping',
            thumbnail: mediaMap?.videoThumbnail2,
            videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
            duration: '18:42',
            category: 'lookbooks',
            views: 62300,
            publishedAt: new Date('2026-01-25').toISOString(),
        },
        {
            title: 'My Autumn Capsule Wardrobe — Style Secrets',
            slug: 'capsule-wardrobe-secrets',
            thumbnail: mediaMap?.videoThumbnail3,
            videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
            duration: '15:08',
            category: 'lookbooks',
            views: 124500,
            publishedAt: new Date('2026-01-15').toISOString(),
        },
        {
            title: 'Candle Making Workshop — DIY Autumn Scents',
            slug: 'candle-making-diy',
            thumbnail: mediaMap?.videoThumbnail4,
            videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
            duration: '32:00',
            category: 'lifestyle',
            views: 41200,
            publishedAt: new Date('2026-02-05').toISOString(),
        },
    ]

    await payload.updateGlobal({
        slug: 'watch-page',
        data: {
            pageEnabled: true,
            heroEnabled: true,
            heroHeading: 'Cinematic Vlogs',
            heroHeadingFont: fontMap?.playfairDisplay,
            heroHeadingColor: '#4a4b34',
            heroSubheading: 'Autumn 2026 Collection & Global Journeys',
            heroSubheadingFont: fontMap?.cormorantGaramond,
            heroSubheadingColor: '#6b6c4f',
            featuredVideoEnabled: true,
            featuredVideoBadge: 'New Release',
            featuredVideoBadgeColor: '#B88078',
            featuredVideoBadgeTextColor: '#F2EBD0',
            featuredVideoTitle: 'A Week in the Cotswolds — Autumn Travel Vlog',
            featuredVideoTitleFont: fontMap?.playfairDisplay,
            featuredVideoTitleColor: '#4a4b34',
            featuredVideoThumbnail: mediaMap?.videoThumbnail1,
            featuredVideoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
            featuredVideoDuration: '24:15',
            featuredVideoDescription: 'Join me for a serene week in the English countryside, from misty morning walks through golden fields to cozy evenings by the fire. Discover hidden villages, local artisans, and the quiet magic of autumn in the Cotswolds.',
            playerBorderEnabled: true,
            playerBorderColor: '#C49A48',
            playButtonColor: '#B88078',
            categoriesEnabled: true,
            categories: [
                { name: 'All Collections', slug: 'all' },
                { name: 'Autumn Lookbooks', slug: 'lookbooks' },
                { name: 'Luxury Travel', slug: 'travel' },
                { name: 'Beauty Masterclass', slug: 'beauty' },
                { name: 'Behind the Scenes', slug: 'bts' },
                { name: 'Lifestyle', slug: 'lifestyle' },
            ],
            categoryPillActiveColor: '#4a4b34',
            categoryPillActiveTextColor: '#F2EBD0',
            categoryPillInactiveColor: '#F2EBD0',
            categoryPillInactiveTextColor: '#4a4b34',
            galleryEnabled: true,
            gallerySectionTitle: 'Latest Vlogs',
            gallerySectionTitleFont: fontMap?.playfairDisplay,
            gallerySectionTitleColor: '#4a4b34',
            galleryBorderAccentColor: '#C49A48',
            galleryColumns: '2',
            galleryGap: 'gap-6',
            videos: galleryVideos as any,
            videoCardTitleFont: fontMap?.playfairDisplay,
            videoCardTitleColor: '#4a4b34',
            videoCardCategoryColor: '#B88078',
            videoCardViewsColor: '#6b6c4f',
            videoCardPlayButtonColor: '#B88078',
            videoCardDurationBgColor: '#4a4b34',
            videoCardDurationTextColor: '#F2EBD0',
            subscribeCardEnabled: true,
            subscribeCardBackgroundColor: '#F2EBD0',
            subscribeCardHeading: 'Never Miss a Video',
            subscribeCardHeadingFont: fontMap?.playfairDisplay,
            subscribeCardHeadingColor: '#4a4b34',
            subscribeCardDescription: 'Subscribe to get notified when new videos are published.',
            subscribeCardDescriptionColor: '#6b6c4f',
            subscribeButtonText: 'Subscribe',
            subscribeButtonUrl: 'https://youtube.com',
            subscribeButtonBgColor: '#4a4b34',
            subscribeButtonTextColor: '#F2EBD0',
            showYouTubeStats: true,
            youtubeSubscriberCount: '124K',
            youtubeTotalViews: '4.2M',
            mustWatchEnabled: true,
            mustWatchBackgroundColor: '#F2EBD0',
            mustWatchBorderColor: '#C49A48',
            mustWatchHeading: 'Must Watch',
            mustWatchHeadingFont: fontMap?.playfairDisplay,
            mustWatchHeadingColor: '#4a4b34',
            mustWatchItems: [
                { title: 'Morning Routine: Autumn Edition', subtitle: '850K views • 2 weeks ago', image: mediaMap?.mustWatch1, videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ' },
                { title: 'Vintage Shopping in Paris', subtitle: '620K views • 1 month ago', image: mediaMap?.mustWatch2, videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ' },
                { title: 'My Capsule Wardrobe Secrets', subtitle: '1.2M views • 3 months ago', image: mediaMap?.mustWatch3, videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ' },
            ],
            mustWatchTitleColor: '#4a4b34',
            mustWatchSubtitleColor: '#6b6c4f',
            socialFollowEnabled: true,
            socialFollowHeading: 'Follow on Socials',
            socialFollowHeadingFont: fontMap?.playfairDisplay,
            socialFollowHeadingColor: '#4a4b34',
            socialLinks: [
                { platform: 'youtube', materialIcon: 'smart_display', url: 'https://youtube.com' },
                { platform: 'instagram', materialIcon: 'camera', url: 'https://instagram.com' },
                { platform: 'tiktok', materialIcon: 'share', url: 'https://tiktok.com' },
            ],
            socialIconColor: '#4a4b34',
            socialIconHoverColor: '#B88078',
            socialSectionBorderColor: '#C49A48',
            playlistsEnabled: true,
            playlistsSectionHeading: 'Video Playlists',
            playlistsSectionHeadingFont: fontMap?.playfairDisplay,
            playlistsSectionHeadingColor: '#4a4b34',
            playlists: [
                { name: 'Travel Diaries', description: 'Explore the world through my lens', coverImage: mediaMap?.playlistCover1, videoCount: 24, youtubePlaylistUrl: 'https://youtube.com' },
                { name: 'Beauty & Skincare', description: 'Tips, routines, and product reviews', coverImage: mediaMap?.playlistCover2, videoCount: 18, youtubePlaylistUrl: 'https://youtube.com' },
                { name: 'Fashion Lookbooks', description: 'Seasonal styling inspiration', coverImage: mediaMap?.playlistCover3, videoCount: 32, youtubePlaylistUrl: 'https://youtube.com' },
            ],
            playlistCardBgColor: '#F2EBD0',
            playlistCardBorderColor: '#C49A48',
            pageBackgroundColor: '#F2EBD0',
            primaryAccentColor: '#B88078',
            secondaryBackgroundColor: '#F2EBD0',
            cardBackgroundColor: '#F2EBD0',
            borderColor: '#C49A48',
            textColor: '#4a4b34',
            mutedTextColor: '#6b6c4f',
            showSidebar: true,
            sidebarPosition: 'right',
            maxContentWidth: '7xl',
        },
    })
    console.log('✅ Watch Page seeded (4 videos)')

    // Seed Contact Page
    await payload.updateGlobal({
        slug: 'contact-page',
        data: {
            pageEnabled: true,
            heroEnabled: true,
            heroHeading: 'Get In Touch',
            heroHeadingFont: fontMap?.playfairDisplay,
            heroHeadingColor: '#4a4b34',
            heroDescription: "Have a question, a project idea, or just want to say hello? I'd love to hear from you and explore how we can work together.",
            heroDescriptionFont: fontMap?.cormorantGaramond,
            heroDescriptionColor: '#6b6c4f',
            contactMethodsEnabled: true,
            contactMethodsHeading: "Let's Start a Conversation",
            contactMethodsHeadingFont: fontMap?.playfairDisplay,
            contactMethodsHeadingColor: '#4a4b34',
            contactMethodsSubheading: 'Choose your preferred way to reach out',
            contactMethods: [
                {
                    iconMaterialSymbol: 'mail',
                    iconColor: '#B88078',
                    title: 'Email Me',
                    titleFont: fontMap?.playfairDisplay,
                    titleColor: '#4a4b34',
                    description: 'For detailed inquiries',
                    value: 'hello@akanksharajpati.com',
                },
                {
                    iconMaterialSymbol: 'location_on',
                    iconColor: '#B88078',
                    title: 'Location',
                    titleFont: fontMap?.playfairDisplay,
                    titleColor: '#4a4b34',
                    description: 'Based in',
                    value: 'London, United Kingdom',
                },
                {
                    iconMaterialSymbol: 'schedule',
                    iconColor: '#B88078',
                    title: 'Response Time',
                    titleFont: fontMap?.playfairDisplay,
                    titleColor: '#4a4b34',
                    description: 'Usually within',
                    value: '24-48 hours',
                },
            ],
            quickResponseEnabled: true,
            quickResponseIcon: 'schedule',
            quickResponseTitle: 'Quick Response Promise',
            quickResponseDescription: 'I typically respond within 24 hours. For urgent matters, feel free to reach out via email directly.',
            quickResponseBgColor: '#B88078',
            quickResponseTextColor: '#F2EBD0',
            formEnabled: true,
            formIcon: 'send',
            formIconColor: '#B88078',
            formHeading: 'Send a Message',
            formHeadingFont: fontMap?.playfairDisplay,
            formHeadingColor: '#4a4b34',
            formBackgroundColor: '#F2EBD0',
            formBorderColor: '#C49A48',
            nameFieldLabel: 'Name',
            nameFieldPlaceholder: 'Your Name',
            emailFieldLabel: 'Email',
            emailFieldPlaceholder: 'your.email@example.com',
            messageFieldLabel: 'Message',
            messageFieldPlaceholder: 'Tell me about your project, ideas, or just say hello...',
            submitButtonText: 'Send Message',
            submitButtonIcon: 'send',
            submitButtonBgColor: '#B88078',
            submitButtonTextColor: '#F2EBD0',
            inputBackgroundColor: '#F2EBD0',
            inputBorderColor: '#C49A48',
            inputTextColor: '#4a4b34',
            labelColor: '#4a4b34',
            servicesEnabled: true,
            servicesHeading: 'What I Can Help You With',
            servicesHeadingFont: fontMap?.playfairDisplay,
            servicesHeadingColor: '#4a4b34',
            servicesDescription: "Whether you're a brand looking for authentic content, a student wanting to learn more, or someone curious about lifestyle and culture, I'm here to help.",
            servicesDescriptionFont: fontMap?.cormorantGaramond,
            servicesDescriptionColor: '#6b6c4f',
            services: [
                {
                    iconEmoji: '🤝',
                    title: 'Brand Collaborations',
                    titleFont: fontMap?.playfairDisplay,
                    titleColor: '#4a4b34',
                    description: 'Interested in partnering for content creation, sponsorships, or lifestyle campaigns? I work with brands that align with my values of authenticity and intentional living.',
                    descriptionColor: '#6b6c4f',
                },
                {
                    iconEmoji: '📚',
                    title: 'Content Creation',
                    titleFont: fontMap?.playfairDisplay,
                    titleColor: '#4a4b34',
                    description: 'Looking for beautifully crafted content for your brand? From photography to video production, I create content that tells compelling stories.',
                    descriptionColor: '#6b6c4f',
                },
                {
                    iconEmoji: '🎙️',
                    title: 'Media & Interview Requests',
                    titleFont: fontMap?.playfairDisplay,
                    titleColor: '#4a4b34',
                    description: 'Journalists, podcasters, and content creators are welcome to reach out for interviews and features on lifestyle topics.',
                    descriptionColor: '#6b6c4f',
                },
                {
                    iconEmoji: '💬',
                    title: 'General Questions',
                    titleFont: fontMap?.playfairDisplay,
                    titleColor: '#4a4b34',
                    description: 'Have questions about my content, seasonal living, or lifestyle topics? I love hearing from my community and answering your curiosity.',
                    descriptionColor: '#6b6c4f',
                },
            ],
            serviceCardBackgroundColor: '#F2EBD0',
            serviceCardBorderColor: '#C49A48',
            faqEnabled: true,
            faqHeading: 'Frequently Asked Questions',
            faqHeadingFont: fontMap?.playfairDisplay,
            faqHeadingColor: '#4a4b34',
            faqDescription: 'Before reaching out, you might find your answer here. These are the most common questions I receive.',
            faqDescriptionFont: fontMap?.cormorantGaramond,
            faqDescriptionColor: '#6b6c4f',
            faqs: [
                { question: 'How quickly do you respond to messages?', questionFont: fontMap?.playfairDisplay, questionColor: '#4a4b34', answer: 'I typically respond within 24-48 hours on business days. For urgent collaboration inquiries, please mention "URGENT" in your subject line.', answerColor: '#6b6c4f' },
                { question: 'Do you accept brand collaborations?', questionFont: fontMap?.playfairDisplay, questionColor: '#4a4b34', answer: 'Yes! I work with brands that align with my content focus on lifestyle, slow living, and seasonal aesthetics. Please share details about your brand and campaign goals.', answerColor: '#6b6c4f' },
                { question: 'Are you available for speaking engagements?', questionFont: fontMap?.playfairDisplay, questionColor: '#4a4b34', answer: "Yes, I'm available for webinars, panels, and speaking events related to content creation, lifestyle, and brand building. Please include event details in your inquiry.", answerColor: '#6b6c4f' },
                { question: 'How can I support your content?', questionFont: fontMap?.playfairDisplay, questionColor: '#4a4b34', answer: 'The best way to support is by subscribing to my YouTube channel, following on Instagram, and sharing content that resonates with you.', answerColor: '#6b6c4f' },
                { question: 'What type of content do you create?', questionFont: fontMap?.playfairDisplay, questionColor: '#4a4b34', answer: 'I create lifestyle content focused on slow living, seasonal transitions, fashion, travel, wellness, and interior design. My content spans written articles, photography, and video.', answerColor: '#6b6c4f' },
                { question: 'Do you offer personal consultations?', questionFont: fontMap?.playfairDisplay, questionColor: '#4a4b34', answer: 'I offer limited personal consultations for brand strategy, content planning, and lifestyle coaching. Please reach out via email with details about your needs.', answerColor: '#6b6c4f' },
            ],
            faqCardBackgroundColor: '#F2EBD0',
            faqCardBorderColor: '#C49A48',
            businessBannerEnabled: true,
            businessBannerBackgroundColor: '#B88078',
            businessBannerHeading: 'For Business Inquiries',
            businessBannerHeadingFont: fontMap?.playfairDisplay,
            businessBannerHeadingColor: '#F2EBD0',
            businessBannerDescription: 'For partnership opportunities and collaborations, please email directly.',
            businessBannerDescriptionFont: fontMap?.cormorantGaramond,
            businessBannerDescriptionColor: '#F2EBD0',
            businessBannerNote: 'business@akanksharajpati.com',
            businessBannerNoteColor: '#F2EBD0',
            pageBackgroundColor: '#F2EBD0',
            primaryAccentColor: '#B88078',
            cardBackgroundColor: '#F2EBD0',
            borderColor: '#C49A48',
            textColor: '#4a4b34',
            mutedTextColor: '#6b6c4f',
        },
    })
    console.log('✅ Contact Page seeded (6 FAQs)')

    console.log('🎉 All globals seeded successfully!')
}
