import { Payload } from 'payload'

export async function seedGlobals(payload: Payload) {
    console.log('🌱 Seeding globals...')

    // Seed Header
    await payload.updateGlobal({
        slug: 'header',
        data: {
            headerBackgroundColor: '#F2EBD0',
            headerTextColor: '#4a4b34',
            ownerName: 'Akanksha Rajpati',
            navItems: [
                { label: 'Home', link: '/' },
                { label: 'About', link: '/about' },
                { label: 'Blog', link: '/blog' },
                { label: 'Shop', link: '/shop' },
                { label: 'Watch', link: '/watch' },
                { label: 'Contact', link: '/contact' },
            ],
            socialLinks: [
                { platform: 'Instagram', url: 'https://instagram.com' },
                { platform: 'YouTube', url: 'https://youtube.com' },
                { platform: 'Pinterest', url: 'https://pinterest.com' },
            ],
            // Theme Settings
            primaryColor: '#B88078',
            secondaryColor: '#C49A48',
            backgroundColor: '#F2EBD0',
            textColor: '#4a4b34',
            mutedTextColor: '#6b6c4f',
            borderColor: '#C49A48',
        },
    })
    console.log('✅ Header seeded')

    // Seed Footer
    await payload.updateGlobal({
        slug: 'footer',
        data: {
            enabled: true,
            brandEnabled: true,
            brandName: 'Akanksha Rajpati',
            brandDescription: 'A luxury lifestyle journal dedicated to the refined aesthetics of the transitional seasons. Based in England, reaching the world.',
            brandNameColor: '#4a4b34',
            brandDescriptionColor: '#6b6c4f',
            discoverLinksEnabled: true,
            discoverLinksHeading: 'Discover',
            discoverLinks: [
                { label: 'Home', link: '/' },
                { label: 'About', link: '/about' },
                { label: 'Blog', link: '/blog' },
                { label: 'Shop', link: '/shop' },
            ],
            infoLinksEnabled: true,
            infoLinksHeading: 'Information',
            infoLinks: [
                { label: 'Privacy Policy', link: '/privacy' },
                { label: 'Terms of Service', link: '/terms' },
                { label: 'Contact', link: '/contact' },
            ],
            newsletterEnabled: true,
            newsletterHeading: 'Stay Inspired',
            newsletterDescription: 'Join our community for exclusive content, early access, and seasonal inspirations.',
            newsletterHeadingColor: '#4a4b34',
            newsletterDescriptionColor: '#6b6c4f',
            newsletterButtonText: 'Subscribe',
            socialLinksEnabled: true,
            socialLinks: [
                { platform: 'Instagram', url: 'https://instagram.com', showIcon: true },
                { platform: 'YouTube', url: 'https://youtube.com', showIcon: true },
                { platform: 'Pinterest', url: 'https://pinterest.com', showIcon: true },
            ],
            copyrightEnabled: true,
            copyrightText: '© 2026 Akanksha Rajpati. All rights reserved.',
            copyrightTextColor: '#6b6c4f',
            // Theme Settings
            primaryColor: '#B88078',
            secondaryColor: '#C49A48',
            backgroundColor: '#F2EBD0',
            textColor: '#4a4b34',
            mutedTextColor: '#6b6c4f',
            borderColor: '#C49A48',
        },
    })
    console.log('✅ Footer seeded')

    // Seed Join Our Inner Circle
    await payload.updateGlobal({
        slug: 'join-our-inner-circle',
        data: {
            enabled: true,
            title: 'Join Our Inner Circle',
            titleColor: '#4a4b34',
            description: 'Subscribe to get exclusive updates, offers, and early access to new content.',
            descriptionColor: '#6b6c4f',
            buttonText: 'Subscribe Now',
            buttonTextColor: '#F2EBD0',
            buttonBackgroundColor: '#4a4b34',
            backgroundColor: '#F2EBD0',
            // Theme Settings
            primaryColor: '#B88078',
            secondaryColor: '#C49A48',
            textColor: '#4a4b34',
            mutedTextColor: '#6b6c4f',
            borderColor: '#C49A48',
            inputBackgroundColor: '#FFFFFF',
        },
    })
    console.log('✅ Join Our Inner Circle seeded')

    // Seed Home Page
    await payload.updateGlobal({
        slug: 'home-page',
        data: {
            pageEnabled: true,
            heroEnabled: true,
            showHeroImage: true,
            heroHeadingLine1: 'Between Summer',
            heroHeadingLine1Color: '#4a4b34',
            heroHeadingLine2: '& Autumn',
            heroHeadingLine2Color: '#B88078',
            heroDescription: 'Capturing the golden transition where warmth meets the crisp morning air, curated for the modern romantic.',
            heroDescriptionColor: '#6b6c4f',
            heroButtonText: 'The Journal',
            heroButtonLink: '/blog',
            heroButtonTextColor: '#F2EBD0',
            heroButtonBgColor: '#4a4b34',
            aboutPreviewEnabled: true,
            showAboutPreviewImage: true,
            aboutPreviewSectionLabel: 'The Creative Vision',
            aboutPreviewSectionLabelColor: '#B88078',
            aboutPreviewHeadingNormal: "Hello, I'm",
            aboutPreviewHeadingNormalColor: '#4a4b34',
            aboutPreviewHeadingAccent: 'Akanksha',
            aboutPreviewHeadingAccentColor: '#B88078',
            aboutPreviewTextMain: 'Welcome to my digital editorial—a dedicated space for slow living, high-end fashion, and the quiet luxury of the autumnal season.',
            aboutPreviewTextMainColor: '#6b6c4f',
            aboutPreviewTextSecondary: "Based in the Cotswolds, I've spent years refining an aesthetic that honors the seasons. This platform serves as a curated guide for those who seek beauty in the mundane and elegance in the everyday.",
            aboutPreviewTextSecondaryColor: '#6b6c4f',
            aboutPreviewButtonText: 'Learn More About My Story',
            aboutPreviewButtonLink: '/about',
            shopPreviewEnabled: true,
            shopPreviewHeadingNormal: 'Shop My',
            shopPreviewHeadingNormalColor: '#4a4b34',
            shopPreviewHeadingAccent: 'Autumn Edits',
            shopPreviewHeadingAccentColor: '#B88078',
            shopPreviewDescription: 'Handpicked pieces for your wardrobe and home.',
            shopPreviewDescriptionColor: '#6b6c4f',
            blogPreviewEnabled: true,
            blogPreviewSectionLabel: 'The Journal',
            blogPreviewSectionLabelColor: '#B88078',
            blogPreviewHeadingNormal: 'Latest',
            blogPreviewHeadingNormalColor: '#4a4b34',
            blogPreviewHeadingAccent: 'Stories',
            blogPreviewHeadingAccentColor: '#B88078',
            blogPreviewButtonText: 'View All Stories',
            blogPreviewButtonLink: '/blog',
            // Theme Settings
            primaryColor: '#B88078',
            secondaryColor: '#C49A48',
            backgroundColor: '#F2EBD0',
            cardBackgroundColor: '#F2EBD0',
            textColor: '#4a4b34',
            mutedTextColor: '#6b6c4f',
            borderColor: '#C49A48',
            buttonPrimaryBgColor: '#4a4b34',
            buttonPrimaryTextColor: '#F2EBD0',
        },
    })
    console.log('✅ Home Page seeded')

    // Seed About Page
    await payload.updateGlobal({
        slug: 'about-page',
        data: {
            pageEnabled: true,
            heroEnabled: true,
            showHeroImage: true,
            sectionLabel: 'The Creative Vision',
            sectionLabelColor: '#B88078',
            headingNormal: "Hello, I'm",
            headingNormalColor: '#4a4b34',
            headingAccent: 'Akanksha Rajpati',
            headingAccentColor: '#B88078',
            introTextMain: 'A lifestyle curator, storyteller, and eternal romantic captivated by the poetry of changing seasons.',
            introTextMainColor: '#6b6c4f',
            introTextSecondary: "Based in the heart of England's countryside, I've dedicated my life to capturing the fleeting beauty that exists between summer's warmth and autumn's embrace.",
            introTextSecondaryColor: '#6b6c4f',
            philosophyEnabled: true,
            philosophyLabel: 'My Philosophy',
            philosophyLabelColor: '#B88078',
            philosophyQuote: '"Beauty lies in the details we often overlook"',
            philosophyQuoteColor: '#4a4b34',
            philosophyText: "Every piece I curate, every story I tell, is rooted in the belief that luxury isn't about excess—it's about intention. It's the warmth of a handwoven throw, the scent of a perfectly blended candle, the way autumn light falls through a window.",
            philosophyTextColor: '#6b6c4f',
            valuesEnabled: true,
            valuesLabel: 'Core Values',
            valuesLabelColor: '#B88078',
            valuesHeadingNormal: 'What I',
            valuesHeadingNormalColor: '#4a4b34',
            valuesHeadingAccent: 'Stand For',
            valuesHeadingAccentColor: '#B88078',
            values: [
                {
                    showIcon: true,
                    title: 'Intentional Living',
                    titleColor: '#4a4b34',
                    description: 'Embracing quality over quantity, mindfulness over haste, and purpose over impulse in every aspect of life.',
                    descriptionColor: '#6b6c4f',
                },
                {
                    showIcon: true,
                    title: 'Seasonal Beauty',
                    titleColor: '#4a4b34',
                    description: 'Finding magic in the changing seasons, celebrating the unique gifts each time of year brings to our lives.',
                    descriptionColor: '#6b6c4f',
                },
                {
                    showIcon: true,
                    title: 'Authentic Expression',
                    titleColor: '#4a4b34',
                    description: 'Creating from the heart, sharing genuine experiences, and building connections through honest storytelling.',
                    descriptionColor: '#6b6c4f',
                },
            ],
            // Theme Settings
            primaryColor: '#B88078',
            secondaryColor: '#C49A48',
            backgroundColor: '#F2EBD0',
            cardBackgroundColor: '#F2EBD0',
            textColor: '#4a4b34',
            mutedTextColor: '#6b6c4f',
            borderColor: '#C49A48',
        },
    })
    console.log('✅ About Page seeded')

    // Seed Blog Page
    await payload.updateGlobal({
        slug: 'blog-page',
        data: {
            pageEnabled: true,
            sectionLabel: 'The Journal',
            sectionLabelColor: '#B88078',
            headingNormal: 'Stories &',
            headingNormalColor: '#4a4b34',
            headingAccent: 'Inspirations',
            headingAccentColor: '#B88078',
            description: 'Thoughtful essays on slow living, seasonal transitions, and the art of finding beauty in everyday moments.',
            descriptionColor: '#6b6c4f',
            newsletterHeading: 'Never Miss a Story',
            newsletterHeadingColor: '#4a4b34',
            newsletterText: 'Subscribe to receive our latest articles directly in your inbox.',
            newsletterTextColor: '#6b6c4f',
            newsletterButtonText: 'Subscribe',
            newsletterButtonTextColor: '#F2EBD0',
            shareHeading: 'Share the Inspiration',
            shareHeadingColor: '#4a4b34',
            shareSubheading: 'Help others discover these stories',
            shareSubheadingColor: '#6b6c4f',
            // Theme Settings
            primaryColor: '#B88078',
            secondaryColor: '#C49A48',
            backgroundColor: '#F2EBD0',
            cardBackgroundColor: '#F2EBD0',
            textColor: '#4a4b34',
            mutedTextColor: '#6b6c4f',
            borderColor: '#C49A48',
        },
    })
    console.log('✅ Blog Page seeded')

    // Seed Shop Page
    await payload.updateGlobal({
        slug: 'shop-page',
        data: {
            pageEnabled: true,
            heroEnabled: true,
            heroBackgroundColor: '#F2EBD0',
            showHeroImage: true,
            heroSectionLabel: 'Autumn Collection 2026',
            heroSectionLabelColor: '#B88078',
            heroHeading: 'Curated Living: Books & Digital',
            heroHeadingColor: '#4a4b34',
            heroDescription: 'A collection designed for the slow-living enthusiast. Elevate your coffee table and digital workspace with our signature earth-toned aesthetics.',
            heroDescriptionColor: '#6b6c4f',
            heroPrimaryButtonEnabled: true,
            heroPrimaryButtonText: 'Browse Collection',
            heroPrimaryButtonLink: '#shop',
            heroPrimaryButtonBgColor: '#4a4b34',
            heroPrimaryButtonTextColor: '#F2EBD0',
            heroSecondaryButtonEnabled: true,
            heroSecondaryButtonText: 'Digital Assets',
            heroSecondaryButtonLink: '#digital',
            heroSecondaryButtonBorderColor: '#4a4b34',
            heroSecondaryButtonTextColor: '#4a4b34',
            categories: [
                { name: 'All', slug: 'all' },
                { name: 'Books', slug: 'books' },
                { name: 'Digital', slug: 'digital' },
                { name: 'Home Decor', slug: 'home-decor' },
                { name: 'Stationery', slug: 'stationery' },
            ],
            categoryActiveColor: '#4a4b34',
            categoryInactiveColor: '#6b6c4f',
            productsEnabled: true,
            // Note: Products array removed because image field is required and needs uploaded media
            // Products can be added via CMS admin panel after uploading images
            productNameColor: '#4a4b34',
            productPriceColor: '#B88078',
            productCategoryColor: '#6b6c4f',
            bannerEnabled: true,
            bannerBackgroundColor: '#F2EBD0',
            bannerSectionLabel: 'Limited Edition',
            bannerSectionLabelColor: '#B88078',
            bannerHeading: 'The Autumn Journal Collection',
            bannerHeadingColor: '#4a4b34',
            bannerDescription: 'A carefully curated bundle featuring our bestselling journal, digital planner, and signature candle. Available while supplies last.',
            bannerDescriptionColor: '#6b6c4f',
            bannerButtonText: 'Shop the Bundle — $180',
            bannerButtonBgColor: '#4a4b34',
            bannerButtonTextColor: '#F2EBD0',
            pageBackgroundColor: '#F2EBD0',
            // Theme Settings
            cardBackgroundColor: '#F2EBD0',
            borderColor: '#C49A48',
        },
    })
    console.log('✅ Shop Page seeded')

    // Seed Watch Page
    await payload.updateGlobal({
        slug: 'watch-page',
        data: {
            pageEnabled: true,
            heroEnabled: true,
            heroHeading: 'Cinematic Vlogs',
            heroHeadingColor: '#4a4b34',
            heroSubheading: 'Autumn 2026 Collection & Global Journeys',
            heroSubheadingColor: '#6b6c4f',
            featuredVideoEnabled: true,
            featuredVideoBadge: 'Featured',
            featuredVideoBadgeColor: '#B88078',
            featuredVideoBadgeTextColor: '#F2EBD0',
            featuredVideoTitle: 'A Week in the Cotswolds',
            featuredVideoTitleColor: '#4a4b34',
            featuredVideoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
            playerBorderColor: '#C49A48',
            playButtonColor: '#B88078',
            categoriesEnabled: true,
            categories: [
                { name: 'All Collections', slug: 'all' },
                { name: 'Autumn Lookbooks', slug: 'lookbooks' },
                { name: 'Luxury Travel', slug: 'travel' },
                { name: 'Beauty Masterclass', slug: 'beauty' },
                { name: 'Behind the Scenes', slug: 'bts' },
                { name: 'Lifestyle', slug: 'lifestyle' },
            ],
            categoryPillActiveColor: '#4a4b34',
            categoryPillActiveTextColor: '#F2EBD0',
            categoryPillInactiveColor: '#F2EBD0',
            categoryPillInactiveTextColor: '#4a4b34',
            galleryEnabled: true,
            gallerySectionTitle: 'Latest Vlogs',
            gallerySectionTitleColor: '#4a4b34',
            galleryBorderAccentColor: '#C49A48',
            galleryColumns: '2',
            // Note: Videos array removed because thumbnail field is required and needs uploaded media
            // Videos can be added via CMS admin panel after uploading thumbnails
            videoCardTitleColor: '#4a4b34',
            videoCardCategoryColor: '#B88078',
            videoCardViewsColor: '#6b6c4f',
            videoCardPlayButtonColor: '#B88078',
            videoCardDurationBgColor: '#4a4b34',
            videoCardDurationTextColor: '#F2EBD0',
            subscribeCardEnabled: true,
            subscribeCardBackgroundColor: '#F2EBD0',
            subscribeCardHeading: 'Never Miss a Video',
            subscribeCardHeadingColor: '#4a4b34',
            subscribeCardDescription: 'Subscribe to get notified when new videos are published.',
            subscribeCardDescriptionColor: '#6b6c4f',
            subscribeButtonText: 'Subscribe',
            subscribeButtonBgColor: '#4a4b34',
            subscribeButtonTextColor: '#F2EBD0',
            mustWatchEnabled: true,
            mustWatchBackgroundColor: '#F2EBD0',
            mustWatchBorderColor: '#C49A48',
            mustWatchHeading: 'Must Watch',
            mustWatchHeadingColor: '#4a4b34',
            mustWatchItems: [
                { title: 'Morning Routine: Autumn Edition', subtitle: '850K views • 2 weeks ago' },
                { title: 'Vintage Shopping in Paris', subtitle: '620K views • 1 month ago' },
                { title: 'My Capsule Wardrobe Secrets', subtitle: '1.2M views • 3 months ago' },
            ],
            mustWatchTitleColor: '#4a4b34',
            mustWatchSubtitleColor: '#6b6c4f',
            socialFollowEnabled: true,
            socialFollowHeading: 'Follow on Socials',
            socialFollowHeadingColor: '#4a4b34',
            socialLinks: [
                { platform: 'youtube', materialIcon: 'smart_display', url: 'https://youtube.com' },
                { platform: 'instagram', materialIcon: 'camera', url: 'https://instagram.com' },
                { platform: 'tiktok', materialIcon: 'share', url: 'https://tiktok.com' },
            ],
            socialIconColor: '#4a4b34',
            socialIconHoverColor: '#B88078',
            socialSectionBorderColor: '#C49A48',
            playlistsEnabled: true,
            playlistsSectionHeading: 'Video Playlists',
            playlistsSectionHeadingColor: '#4a4b34',
            playlists: [
                { name: 'Travel Diaries', description: 'Explore the world through my lens', videoCount: 24 },
                { name: 'Beauty & Skincare', description: 'Tips, routines, and product reviews', videoCount: 18 },
                { name: 'Fashion Lookbooks', description: 'Seasonal styling inspiration', videoCount: 32 },
            ],
            playlistCardBgColor: '#F2EBD0',
            playlistCardBorderColor: '#C49A48',
            pageBackgroundColor: '#F2EBD0',
            primaryAccentColor: '#B88078',
            secondaryBackgroundColor: '#F2EBD0',
            cardBackgroundColor: '#F2EBD0',
            borderColor: '#C49A48',
            textColor: '#4a4b34',
            mutedTextColor: '#6b6c4f',
            // Theme Settings
        },
    })
    console.log('✅ Watch Page seeded')

    // Seed Contact Page
    await payload.updateGlobal({
        slug: 'contact-page',
        data: {
            pageEnabled: true,
            heroEnabled: true,
            heroHeading: 'Get In Touch',
            heroHeadingColor: '#4a4b34',
            heroDescription: "Have a question, a project idea, or just want to say hello? I'd love to hear from you and explore how we can work together.",
            heroDescriptionColor: '#6b6c4f',
            contactMethodsEnabled: true,
            contactMethodsHeading: "Let's Start a Conversation",
            contactMethodsHeadingColor: '#4a4b34',
            contactMethodsSubheading: 'Choose your preferred way to reach out',
            contactMethods: [
                {
                    iconMaterialSymbol: 'mail',
                    iconColor: '#B88078',
                    title: 'Email Me',
                    titleColor: '#4a4b34',
                    description: 'For detailed inquiries',
                    value: 'hello@akanksharajpati.com',
                },
                {
                    iconMaterialSymbol: 'location_on',
                    iconColor: '#B88078',
                    title: 'Location',
                    titleColor: '#4a4b34',
                    description: 'Based in',
                    value: 'London, United Kingdom',
                },
                {
                    iconMaterialSymbol: 'schedule',
                    iconColor: '#B88078',
                    title: 'Response Time',
                    titleColor: '#4a4b34',
                    description: 'Usually within',
                    value: '24-48 hours',
                },
            ],
            quickResponseEnabled: true,
            quickResponseIcon: 'schedule',
            quickResponseTitle: 'Quick Response Promise',
            quickResponseDescription: 'I typically respond within 24 hours. For urgent matters, feel free to call directly.',
            quickResponseBgColor: '#B88078',
            quickResponseTextColor: '#F2EBD0',
            formEnabled: true,
            formIcon: 'send',
            formIconColor: '#B88078',
            formHeading: 'Send a Message',
            formHeadingColor: '#4a4b34',
            formBackgroundColor: '#F2EBD0',
            formBorderColor: '#C49A48',
            nameFieldLabel: 'Name',
            nameFieldPlaceholder: 'Your Name',
            emailFieldLabel: 'Email',
            emailFieldPlaceholder: 'your.email@example.com',
            messageFieldLabel: 'Message',
            messageFieldPlaceholder: 'Tell me about your project, ideas, or just say hello...',
            submitButtonText: 'Send Message',
            submitButtonIcon: 'send',
            submitButtonBgColor: '#B88078',
            submitButtonTextColor: '#F2EBD0',
            inputBackgroundColor: '#F2EBD0',
            inputBorderColor: '#C49A48',
            inputTextColor: '#4a4b34',
            labelColor: '#4a4b34',
            servicesEnabled: true,
            servicesHeading: 'What I Can Help You With',
            servicesHeadingColor: '#4a4b34',
            servicesDescription: "Whether you're a brand looking for authentic content, a student wanting to learn more, or someone curious about lifestyle and culture, I'm here to help.",
            servicesDescriptionColor: '#6b6c4f',
            services: [
                {
                    iconEmoji: '🤝',
                    title: 'Brand Collaborations',
                    titleColor: '#4a4b34',
                    description: 'Interested in partnering for content creation, sponsorships, or lifestyle campaigns? I work with brands that align with my values of authenticity and intentional living.',
                    descriptionColor: '#6b6c4f',
                },
                {
                    iconEmoji: '📚',
                    title: 'Content Creation',
                    titleColor: '#4a4b34',
                    description: 'Looking for beautifully crafted content for your brand? From photography to video production, I create content that tells compelling stories.',
                    descriptionColor: '#6b6c4f',
                },
                {
                    iconEmoji: '🎙️',
                    title: 'Media & Interview Requests',
                    titleColor: '#4a4b34',
                    description: 'Journalists, podcasters, and content creators are welcome to reach out for interviews and features on lifestyle topics.',
                    descriptionColor: '#6b6c4f',
                },
                {
                    iconEmoji: '💬',
                    title: 'General Questions',
                    titleColor: '#4a4b34',
                    description: 'Have questions about my content, seasonal living, or lifestyle topics? I love hearing from my community and answering your curiosity.',
                    descriptionColor: '#6b6c4f',
                },
            ],
            serviceCardBackgroundColor: '#F2EBD0',
            serviceCardBorderColor: '#C49A48',
            faqEnabled: true,
            faqHeading: 'Frequently Asked Questions',
            faqHeadingColor: '#4a4b34',
            faqDescription: 'Before reaching out, you might find your answer here. These are the most common questions I receive.',
            faqDescriptionColor: '#6b6c4f',
            faqs: [
                {
                    question: 'How quickly do you respond to messages?',
                    questionColor: '#4a4b34',
                    answer: 'I typically respond within 24-48 hours on business days. For urgent collaboration inquiries, please mention "URGENT" in your subject line.',
                    answerColor: '#6b6c4f',
                },
                {
                    question: 'Do you accept brand collaborations?',
                    questionColor: '#4a4b34',
                    answer: 'Yes! I work with brands that align with my content focus on lifestyle, slow living, and seasonal aesthetics. Please share details about your brand and campaign goals.',
                    answerColor: '#6b6c4f',
                },
                {
                    question: 'Are you available for speaking engagements?',
                    questionColor: '#4a4b34',
                    answer: "Yes, I'm available for webinars, panels, and speaking events related to content creation, lifestyle, and brand building. Please include event details in your inquiry.",
                    answerColor: '#6b6c4f',
                },
                {
                    question: 'How can I support your content?',
                    questionColor: '#4a4b34',
                    answer: 'The best way to support is by subscribing to my YouTube channel, following on Instagram, and sharing content that resonates with you.',
                    answerColor: '#6b6c4f',
                },
            ],
            faqCardBackgroundColor: '#F2EBD0',
            faqCardBorderColor: '#C49A48',
            businessBannerEnabled: true,
            businessBannerHeading: 'For Business Inquiries',
            businessBannerHeadingColor: '#F2EBD0',
            businessBannerDescription: 'For partnership opportunities and collaborations, please email directly.',
            businessBannerDescriptionColor: '#F2EBD0',
            businessBannerNote: 'business@akanksharajpati.com',
            businessBannerNoteColor: '#F2EBD0',
            businessBannerBackgroundColor: '#B88078',
            pageBackgroundColor: '#F2EBD0',
            primaryAccentColor: '#B88078',
            cardBackgroundColor: '#F2EBD0',
            borderColor: '#C49A48',
            textColor: '#4a4b34',
            mutedTextColor: '#6b6c4f',
        },
    })
    console.log('✅ Contact Page seeded')

    console.log('🎉 All globals seeded successfully!')
}
