/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    articles: Article;
    'article-authors': ArticleAuthor;
    comments: Comment;
    media: Media;
    fonts: Font;
    users: User;
    roles: Role;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    'article-authors': ArticleAuthorsSelect<false> | ArticleAuthorsSelect<true>;
    comments: CommentsSelect<false> | CommentsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    fonts: FontsSelect<false> | FontsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    roles: RolesSelect<false> | RolesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'home-page': HomePage;
    'blog-page': BlogPage;
    'about-page': AboutPage;
    'shop-page': ShopPage;
    'contact-page': ContactPage;
    'watch-page': WatchPage;
    header: Header;
    footer: Footer;
    'join-our-inner-circle': JoinOurInnerCircle;
  };
  globalsSelect: {
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'blog-page': BlogPageSelect<false> | BlogPageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'shop-page': ShopPageSelect<false> | ShopPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    'watch-page': WatchPageSelect<false> | WatchPageSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'join-our-inner-circle': JoinOurInnerCircleSelect<false> | JoinOurInnerCircleSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: string;
  title: string;
  slug: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Image or media displayed between content and summary (optional)
   */
  featuredMedia?: (string | null) | Media;
  /**
   * Optional caption for the featured media
   */
  featuredMediaCaption?: string | null;
  contentSummary: string;
  /**
   * Automatically calculated but can be overridden manually
   */
  readTimeInMins?: number | null;
  /**
   * Total number of views
   */
  views?: number | null;
  coverImage?: (string | null) | Media;
  author: string | ArticleAuthor;
  status: 'Draft' | 'Published';
  category: string;
  publishedAt?: string | null;
  relatedProducts?:
    | {
        name: string;
        price: string;
        category?: string | null;
        image: string | Media;
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Leave empty to auto-generate
   */
  alt?: string | null;
  blurDataUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "article-authors".
 */
export interface ArticleAuthor {
  id: string;
  name: string;
  avatar?: (string | null) | Media;
  role: string;
  bio?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments".
 */
export interface Comment {
  id: string;
  content: string;
  authorName: string;
  /**
   * Kept private, not shown on frontend
   */
  authorEmail?: string | null;
  article: string | Article;
  status: 'pending' | 'approved' | 'rejected';
  parent?: (string | null) | Comment;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fonts".
 */
export interface Font {
  id: string;
  name: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  avatar?: (string | null) | Media;
  /**
   * Contact an owner to change your role
   */
  role: string | Role;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles".
 */
export interface Role {
  id: string;
  name: string;
  /**
   * Brief description of what this role allows
   */
  description?: string | null;
  /**
   * If checked, this role bypasses ALL permission checks (like Super Admin)
   */
  isOwner?: boolean | null;
  content?: {
    articles?: {
      read?: boolean | null;
      create?: boolean | null;
      update?: boolean | null;
      delete?: boolean | null;
    };
    articleAuthors?: {
      read?: boolean | null;
      create?: boolean | null;
      update?: boolean | null;
      delete?: boolean | null;
    };
    comments?: {
      read?: boolean | null;
      create?: boolean | null;
      update?: boolean | null;
      delete?: boolean | null;
    };
  };
  pages?: {
    homePage?: {
      read?: boolean | null;
      update?: boolean | null;
    };
    blogPage?: {
      read?: boolean | null;
      update?: boolean | null;
    };
    aboutPage?: {
      read?: boolean | null;
      update?: boolean | null;
    };
    shopPage?: {
      read?: boolean | null;
      update?: boolean | null;
    };
    contactPage?: {
      read?: boolean | null;
      update?: boolean | null;
    };
    watchPage?: {
      read?: boolean | null;
      update?: boolean | null;
    };
  };
  design?: {
    header?: {
      read?: boolean | null;
      update?: boolean | null;
    };
    footer?: {
      read?: boolean | null;
      update?: boolean | null;
    };
    joinOurInnerCircle?: {
      read?: boolean | null;
      update?: boolean | null;
    };
  };
  media?: {
    mediaFiles?: {
      read?: boolean | null;
      create?: boolean | null;
      update?: boolean | null;
      delete?: boolean | null;
    };
    fonts?: {
      read?: boolean | null;
      create?: boolean | null;
      update?: boolean | null;
      delete?: boolean | null;
    };
  };
  admin?: {
    users?: {
      read?: boolean | null;
      create?: boolean | null;
      update?: boolean | null;
      delete?: boolean | null;
    };
    roles?: {
      read?: boolean | null;
      create?: boolean | null;
      update?: boolean | null;
      delete?: boolean | null;
    };
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'articles';
        value: string | Article;
      } | null)
    | ({
        relationTo: 'article-authors';
        value: string | ArticleAuthor;
      } | null)
    | ({
        relationTo: 'comments';
        value: string | Comment;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'fonts';
        value: string | Font;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'roles';
        value: string | Role;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  featuredMedia?: T;
  featuredMediaCaption?: T;
  contentSummary?: T;
  readTimeInMins?: T;
  views?: T;
  coverImage?: T;
  author?: T;
  status?: T;
  category?: T;
  publishedAt?: T;
  relatedProducts?:
    | T
    | {
        name?: T;
        price?: T;
        category?: T;
        image?: T;
        link?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "article-authors_select".
 */
export interface ArticleAuthorsSelect<T extends boolean = true> {
  name?: T;
  avatar?: T;
  role?: T;
  bio?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments_select".
 */
export interface CommentsSelect<T extends boolean = true> {
  content?: T;
  authorName?: T;
  authorEmail?: T;
  article?: T;
  status?: T;
  parent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  blurDataUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fonts_select".
 */
export interface FontsSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  avatar?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles_select".
 */
export interface RolesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  isOwner?: T;
  content?:
    | T
    | {
        articles?:
          | T
          | {
              read?: T;
              create?: T;
              update?: T;
              delete?: T;
            };
        articleAuthors?:
          | T
          | {
              read?: T;
              create?: T;
              update?: T;
              delete?: T;
            };
        comments?:
          | T
          | {
              read?: T;
              create?: T;
              update?: T;
              delete?: T;
            };
      };
  pages?:
    | T
    | {
        homePage?:
          | T
          | {
              read?: T;
              update?: T;
            };
        blogPage?:
          | T
          | {
              read?: T;
              update?: T;
            };
        aboutPage?:
          | T
          | {
              read?: T;
              update?: T;
            };
        shopPage?:
          | T
          | {
              read?: T;
              update?: T;
            };
        contactPage?:
          | T
          | {
              read?: T;
              update?: T;
            };
        watchPage?:
          | T
          | {
              read?: T;
              update?: T;
            };
      };
  design?:
    | T
    | {
        header?:
          | T
          | {
              read?: T;
              update?: T;
            };
        footer?:
          | T
          | {
              read?: T;
              update?: T;
            };
        joinOurInnerCircle?:
          | T
          | {
              read?: T;
              update?: T;
            };
      };
  media?:
    | T
    | {
        mediaFiles?:
          | T
          | {
              read?: T;
              create?: T;
              update?: T;
              delete?: T;
            };
        fonts?:
          | T
          | {
              read?: T;
              create?: T;
              update?: T;
              delete?: T;
            };
      };
  admin?:
    | T
    | {
        users?:
          | T
          | {
              read?: T;
              create?: T;
              update?: T;
              delete?: T;
            };
        roles?:
          | T
          | {
              read?: T;
              create?: T;
              update?: T;
              delete?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: string;
  /**
   * If disabled, a coming soon message will be shown
   */
  pageEnabled?: boolean | null;
  heroEnabled?: boolean | null;
  /**
   * If disabled, the hero section will show without the background image
   */
  showHeroImage?: boolean | null;
  heroImage?: (string | null) | Media;
  heroHeadingLine1?: string | null;
  heroHeadingLine1Font?: (string | null) | Font;
  heroHeadingLine1Color?: string | null;
  heroHeadingLine2?: string | null;
  heroHeadingLine2Font?: (string | null) | Font;
  heroHeadingLine2Color?: string | null;
  heroDescription?: string | null;
  heroDescriptionFont?: (string | null) | Font;
  heroDescriptionColor?: string | null;
  heroButtonText?: string | null;
  heroButtonLink?: string | null;
  heroButtonFont?: (string | null) | Font;
  heroButtonTextColor?: string | null;
  heroButtonBgColor?: string | null;
  aboutPreviewEnabled?: boolean | null;
  /**
   * If disabled, the section will show without the image
   */
  showAboutPreviewImage?: boolean | null;
  aboutPreviewImage?: (string | null) | Media;
  aboutPreviewSectionLabel?: string | null;
  aboutPreviewSectionLabelFont?: (string | null) | Font;
  aboutPreviewSectionLabelColor?: string | null;
  aboutPreviewHeadingNormal?: string | null;
  aboutPreviewHeadingNormalFont?: (string | null) | Font;
  aboutPreviewHeadingNormalColor?: string | null;
  aboutPreviewHeadingAccent?: string | null;
  aboutPreviewHeadingAccentFont?: (string | null) | Font;
  aboutPreviewHeadingAccentColor?: string | null;
  aboutPreviewTextMain?: string | null;
  aboutPreviewTextMainFont?: (string | null) | Font;
  aboutPreviewTextMainColor?: string | null;
  aboutPreviewTextSecondary?: string | null;
  aboutPreviewTextSecondaryFont?: (string | null) | Font;
  aboutPreviewTextSecondaryColor?: string | null;
  aboutPreviewButtonText?: string | null;
  aboutPreviewButtonLink?: string | null;
  shopPreviewEnabled?: boolean | null;
  shopPreviewSectionLabel?: string | null;
  shopPreviewSectionLabelFont?: (string | null) | Font;
  shopPreviewSectionLabelColor?: string | null;
  shopPreviewHeadingNormal?: string | null;
  shopPreviewHeadingNormalFont?: (string | null) | Font;
  shopPreviewHeadingNormalColor?: string | null;
  shopPreviewHeadingAccent?: string | null;
  shopPreviewHeadingAccentFont?: (string | null) | Font;
  shopPreviewHeadingAccentColor?: string | null;
  shopPreviewDescription?: string | null;
  shopPreviewDescriptionFont?: (string | null) | Font;
  shopPreviewDescriptionColor?: string | null;
  shopPreviewButtonText?: string | null;
  shopPreviewButtonLink?: string | null;
  blogPreviewEnabled?: boolean | null;
  blogPreviewSectionLabel?: string | null;
  blogPreviewSectionLabelFont?: (string | null) | Font;
  blogPreviewSectionLabelColor?: string | null;
  blogPreviewHeadingNormal?: string | null;
  blogPreviewHeadingNormalFont?: (string | null) | Font;
  blogPreviewHeadingNormalColor?: string | null;
  blogPreviewHeadingAccent?: string | null;
  blogPreviewHeadingAccentFont?: (string | null) | Font;
  blogPreviewHeadingAccentColor?: string | null;
  blogPreviewButtonText?: string | null;
  blogPreviewButtonLink?: string | null;
  watchPreviewEnabled?: boolean | null;
  watchPreviewSectionLabel?: string | null;
  watchPreviewSectionLabelFont?: (string | null) | Font;
  watchPreviewSectionLabelColor?: string | null;
  watchPreviewHeadingNormal?: string | null;
  watchPreviewHeadingNormalFont?: (string | null) | Font;
  watchPreviewHeadingNormalColor?: string | null;
  watchPreviewHeadingAccent?: string | null;
  watchPreviewHeadingAccentFont?: (string | null) | Font;
  watchPreviewHeadingAccentColor?: string | null;
  watchPreviewDescription?: string | null;
  watchPreviewDescriptionFont?: (string | null) | Font;
  watchPreviewDescriptionColor?: string | null;
  watchPreviewButtonText?: string | null;
  watchPreviewButtonLink?: string | null;
  contactPreviewEnabled?: boolean | null;
  contactPreviewSectionLabel?: string | null;
  contactPreviewSectionLabelFont?: (string | null) | Font;
  contactPreviewSectionLabelColor?: string | null;
  contactPreviewHeadingNormal?: string | null;
  contactPreviewHeadingNormalFont?: (string | null) | Font;
  contactPreviewHeadingNormalColor?: string | null;
  contactPreviewHeadingAccent?: string | null;
  contactPreviewHeadingAccentFont?: (string | null) | Font;
  contactPreviewHeadingAccentColor?: string | null;
  contactPreviewDescription?: string | null;
  contactPreviewDescriptionFont?: (string | null) | Font;
  contactPreviewDescriptionColor?: string | null;
  contactPreviewButtonText?: string | null;
  contactPreviewButtonLink?: string | null;
  /**
   * Main accent color (Dusty Rose)
   */
  primaryColor?: string | null;
  /**
   * Secondary accent color (Golden)
   */
  secondaryColor?: string | null;
  /**
   * Main page background color (Cream)
   */
  backgroundColor?: string | null;
  /**
   * Background color for cards
   */
  cardBackgroundColor?: string | null;
  /**
   * Main text color (Dark Olive)
   */
  textColor?: string | null;
  /**
   * Secondary/muted text color (Muted Olive)
   */
  mutedTextColor?: string | null;
  /**
   * Default border color (Golden)
   */
  borderColor?: string | null;
  /**
   * Background color for primary buttons
   */
  buttonPrimaryBgColor?: string | null;
  /**
   * Text color for primary buttons
   */
  buttonPrimaryTextColor?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-page".
 */
export interface BlogPage {
  id: string;
  /**
   * If disabled, a coming soon message will be shown
   */
  pageEnabled?: boolean | null;
  headerEnabled?: boolean | null;
  sectionLabel: string;
  sectionLabelFont?: (string | null) | Font;
  sectionLabelColor?: string | null;
  headingNormal: string;
  headingNormalFont?: (string | null) | Font;
  headingNormalColor?: string | null;
  headingAccent: string;
  headingAccentFont?: (string | null) | Font;
  headingAccentColor?: string | null;
  description: string;
  descriptionFont?: (string | null) | Font;
  descriptionColor?: string | null;
  newsletterHeading: string;
  newsletterHeadingFont?: (string | null) | Font;
  newsletterHeadingColor?: string | null;
  newsletterText: string;
  newsletterTextFont?: (string | null) | Font;
  newsletterTextColor?: string | null;
  newsletterButtonText: string;
  newsletterButtonTextFont?: (string | null) | Font;
  newsletterButtonTextColor?: string | null;
  shareHeading: string;
  shareHeadingFont?: (string | null) | Font;
  shareHeadingColor?: string | null;
  shareSubheading: string;
  shareSubheadingFont?: (string | null) | Font;
  shareSubheadingColor?: string | null;
  socialPlatforms?:
    | {
        platform: string;
        /**
         * Use {url} and {title} as placeholders. E.g. https://example.com/share?u={url}
         */
        shareUrl?: string | null;
        /**
         * If disabled, only the text will be shown
         */
        showIcon?: boolean | null;
        /**
         * Upload a custom icon, or leave empty to use the default icon
         */
        icon?: (string | null) | Media;
        /**
         * Override the platform name with custom text. Leave empty to use platform name.
         */
        customText?: string | null;
        /**
         * Custom font for this platform text
         */
        textFont?: (string | null) | Font;
        /**
         * Custom color for this platform text
         */
        textColor?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Main accent color (Dusty Rose)
   */
  primaryColor?: string | null;
  /**
   * Secondary accent color (Golden)
   */
  secondaryColor?: string | null;
  /**
   * Main page background color (Cream)
   */
  backgroundColor?: string | null;
  /**
   * Background color for blog cards
   */
  cardBackgroundColor?: string | null;
  /**
   * Main text color (Dark Olive)
   */
  textColor?: string | null;
  /**
   * Secondary/muted text color (Muted Olive)
   */
  mutedTextColor?: string | null;
  /**
   * Default border color (Golden)
   */
  borderColor?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: string;
  /**
   * If disabled, a coming soon message will be shown
   */
  pageEnabled?: boolean | null;
  heroEnabled?: boolean | null;
  /**
   * If disabled, the hero section will show without the image
   */
  showHeroImage?: boolean | null;
  heroImage?: (string | null) | Media;
  sectionLabel?: string | null;
  sectionLabelFont?: (string | null) | Font;
  sectionLabelColor?: string | null;
  headingNormal?: string | null;
  headingNormalFont?: (string | null) | Font;
  headingNormalColor?: string | null;
  headingAccent?: string | null;
  headingAccentFont?: (string | null) | Font;
  headingAccentColor?: string | null;
  introTextMain?: string | null;
  introTextMainFont?: (string | null) | Font;
  introTextMainColor?: string | null;
  introTextSecondary?: string | null;
  introTextSecondaryFont?: (string | null) | Font;
  introTextSecondaryColor?: string | null;
  /**
   * If disabled, no signature image will be shown
   */
  showSignatureImage?: boolean | null;
  signatureImage?: (string | null) | Media;
  philosophyEnabled?: boolean | null;
  philosophyLabel?: string | null;
  philosophyLabelFont?: (string | null) | Font;
  philosophyLabelColor?: string | null;
  philosophyQuote?: string | null;
  philosophyQuoteFont?: (string | null) | Font;
  philosophyQuoteColor?: string | null;
  philosophyText?: string | null;
  philosophyTextFont?: (string | null) | Font;
  philosophyTextColor?: string | null;
  valuesEnabled?: boolean | null;
  valuesLabel?: string | null;
  valuesLabelFont?: (string | null) | Font;
  valuesLabelColor?: string | null;
  valuesHeadingNormal?: string | null;
  valuesHeadingNormalFont?: (string | null) | Font;
  valuesHeadingNormalColor?: string | null;
  valuesHeadingAccent?: string | null;
  valuesHeadingAccentFont?: (string | null) | Font;
  valuesHeadingAccentColor?: string | null;
  values?:
    | {
        /**
         * If disabled, only the title and description will be shown
         */
        showIcon?: boolean | null;
        icon?: (string | null) | Media;
        title: string;
        titleFont?: (string | null) | Font;
        titleColor?: string | null;
        description: string;
        descriptionFont?: (string | null) | Font;
        descriptionColor?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Main accent color (Dusty Rose)
   */
  primaryColor?: string | null;
  /**
   * Secondary accent color (Golden)
   */
  secondaryColor?: string | null;
  /**
   * Main page background color (Cream)
   */
  backgroundColor?: string | null;
  /**
   * Background color for cards
   */
  cardBackgroundColor?: string | null;
  /**
   * Main text color (Dark Olive)
   */
  textColor?: string | null;
  /**
   * Secondary/muted text color (Muted Olive)
   */
  mutedTextColor?: string | null;
  /**
   * Default border color (Golden)
   */
  borderColor?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop-page".
 */
export interface ShopPage {
  id: string;
  /**
   * If disabled, a coming soon message will be shown
   */
  pageEnabled?: boolean | null;
  heroEnabled?: boolean | null;
  heroBackgroundColor?: string | null;
  showHeroImage?: boolean | null;
  heroImage?: (string | null) | Media;
  heroImageOpacity?: number | null;
  heroSectionLabel?: string | null;
  heroSectionLabelFont?: (string | null) | Font;
  heroSectionLabelColor?: string | null;
  heroHeading?: string | null;
  heroHeadingFont?: (string | null) | Font;
  heroHeadingColor?: string | null;
  heroDescription?: string | null;
  heroDescriptionFont?: (string | null) | Font;
  heroDescriptionColor?: string | null;
  heroPrimaryButtonEnabled?: boolean | null;
  heroPrimaryButtonText?: string | null;
  heroPrimaryButtonLink?: string | null;
  heroPrimaryButtonFont?: (string | null) | Font;
  heroPrimaryButtonBgColor?: string | null;
  heroPrimaryButtonTextColor?: string | null;
  heroSecondaryButtonEnabled?: boolean | null;
  heroSecondaryButtonText?: string | null;
  heroSecondaryButtonLink?: string | null;
  heroSecondaryButtonFont?: (string | null) | Font;
  heroSecondaryButtonBorderColor?: string | null;
  heroSecondaryButtonTextColor?: string | null;
  filterBarEnabled?: boolean | null;
  categories?:
    | {
        name: string;
        slug?: string | null;
        id?: string | null;
      }[]
    | null;
  categoryFont?: (string | null) | Font;
  categoryActiveColor?: string | null;
  categoryInactiveColor?: string | null;
  showSortDropdown?: boolean | null;
  sortOptions?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  productsEnabled?: boolean | null;
  productsGridColumns?: ('2' | '3' | '4') | null;
  productCardHeight?: number | null;
  showQuickViewButton?: boolean | null;
  quickViewButtonText?: string | null;
  products?:
    | {
        name: string;
        description?: string | null;
        price: string;
        salePrice?: string | null;
        category?: string | null;
        image: string | Media;
        badge?: string | null;
        badgeColor?: string | null;
        link?: string | null;
        isDigital?: boolean | null;
        publishedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  productNameFont?: (string | null) | Font;
  productNameColor?: string | null;
  productPriceFont?: (string | null) | Font;
  productPriceColor?: string | null;
  productCategoryColor?: string | null;
  bannerEnabled?: boolean | null;
  bannerBackgroundColor?: string | null;
  bannerSectionLabel?: string | null;
  bannerSectionLabelFont?: (string | null) | Font;
  bannerSectionLabelColor?: string | null;
  bannerHeading?: string | null;
  bannerHeadingFont?: (string | null) | Font;
  bannerHeadingColor?: string | null;
  bannerDescription?: string | null;
  bannerDescriptionFont?: (string | null) | Font;
  bannerDescriptionColor?: string | null;
  bannerButtonText?: string | null;
  bannerButtonLink?: string | null;
  bannerButtonFont?: (string | null) | Font;
  bannerButtonBgColor?: string | null;
  bannerButtonTextColor?: string | null;
  pageBackgroundColor?: string | null;
  /**
   * Used for buttons, highlights, etc.
   */
  primaryAccentColor?: string | null;
  secondaryAccentColor?: string | null;
  borderColor?: string | null;
  cardBackgroundColor?: string | null;
  cardHoverEffect?: ('scale' | 'shadow' | 'border' | 'none') | null;
  currencySymbol?: string | null;
  currencyPosition?: ('before' | 'after') | null;
  /**
   * Enable for full ecommerce functionality
   */
  showAddToCartButton?: boolean | null;
  addToCartButtonText?: string | null;
  /**
   * Products link to external stores (Etsy, Gumroad, etc.)
   */
  externalCheckoutEnabled?: boolean | null;
  externalCheckoutButtonText?: string | null;
  showOutOfStock?: boolean | null;
  outOfStockText?: string | null;
  showSaleBadge?: boolean | null;
  saleBadgeText?: string | null;
  saleBadgeColor?: string | null;
  emptyStateHeading?: string | null;
  emptyStateDescription?: string | null;
  emptyStateIcon?: (string | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: string;
  /**
   * If disabled, a coming soon message will be shown
   */
  pageEnabled?: boolean | null;
  heroEnabled?: boolean | null;
  heroHeading?: string | null;
  heroHeadingFont?: (string | null) | Font;
  heroHeadingColor?: string | null;
  heroDescription?: string | null;
  heroDescriptionFont?: (string | null) | Font;
  heroDescriptionColor?: string | null;
  contactMethodsEnabled?: boolean | null;
  contactMethodsHeading?: string | null;
  contactMethodsHeadingFont?: (string | null) | Font;
  contactMethodsHeadingColor?: string | null;
  contactMethodsSubheading?: string | null;
  contactMethods?:
    | {
        icon?: (string | null) | Media;
        /**
         * e.g. "mail", "location_on", "schedule"
         */
        iconMaterialSymbol?: string | null;
        iconColor?: string | null;
        title: string;
        titleFont?: (string | null) | Font;
        titleColor?: string | null;
        description?: string | null;
        value?: string | null;
        /**
         * e.g. mailto:email@example.com
         */
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  quickResponseEnabled?: boolean | null;
  quickResponseIcon?: string | null;
  quickResponseTitle?: string | null;
  quickResponseDescription?: string | null;
  quickResponseBgColor?: string | null;
  quickResponseTextColor?: string | null;
  formEnabled?: boolean | null;
  formIcon?: string | null;
  formIconColor?: string | null;
  formHeading?: string | null;
  formHeadingFont?: (string | null) | Font;
  formHeadingColor?: string | null;
  formBackgroundColor?: string | null;
  formBorderColor?: string | null;
  nameFieldLabel?: string | null;
  nameFieldPlaceholder?: string | null;
  emailFieldLabel?: string | null;
  emailFieldPlaceholder?: string | null;
  messageFieldLabel?: string | null;
  messageFieldPlaceholder?: string | null;
  submitButtonText?: string | null;
  submitButtonIcon?: string | null;
  submitButtonBgColor?: string | null;
  submitButtonTextColor?: string | null;
  inputBackgroundColor?: string | null;
  inputBorderColor?: string | null;
  inputTextColor?: string | null;
  labelColor?: string | null;
  servicesEnabled?: boolean | null;
  servicesHeading?: string | null;
  servicesHeadingFont?: (string | null) | Font;
  servicesHeadingColor?: string | null;
  servicesDescription?: string | null;
  servicesDescriptionFont?: (string | null) | Font;
  servicesDescriptionColor?: string | null;
  services?:
    | {
        icon?: (string | null) | Media;
        /**
         * e.g. 🤝, 📚, 🎙️, 💬
         */
        iconEmoji?: string | null;
        title: string;
        titleFont?: (string | null) | Font;
        titleColor?: string | null;
        description?: string | null;
        descriptionColor?: string | null;
        id?: string | null;
      }[]
    | null;
  serviceCardBackgroundColor?: string | null;
  serviceCardBorderColor?: string | null;
  faqEnabled?: boolean | null;
  faqHeading?: string | null;
  faqHeadingFont?: (string | null) | Font;
  faqHeadingColor?: string | null;
  faqDescription?: string | null;
  faqDescriptionFont?: (string | null) | Font;
  faqDescriptionColor?: string | null;
  faqs?:
    | {
        question: string;
        questionFont?: (string | null) | Font;
        questionColor?: string | null;
        answer: string;
        answerColor?: string | null;
        id?: string | null;
      }[]
    | null;
  faqCardBackgroundColor?: string | null;
  faqCardBorderColor?: string | null;
  businessBannerEnabled?: boolean | null;
  businessBannerBackgroundColor?: string | null;
  businessBannerHeading?: string | null;
  businessBannerHeadingFont?: (string | null) | Font;
  businessBannerHeadingColor?: string | null;
  businessBannerDescription?: string | null;
  businessBannerDescriptionFont?: (string | null) | Font;
  businessBannerDescriptionColor?: string | null;
  businessBannerNote?: string | null;
  businessBannerNoteColor?: string | null;
  pageBackgroundColor?: string | null;
  /**
   * Used for buttons, icons, highlights
   */
  primaryAccentColor?: string | null;
  cardBackgroundColor?: string | null;
  borderColor?: string | null;
  textColor?: string | null;
  mutedTextColor?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "watch-page".
 */
export interface WatchPage {
  id: string;
  /**
   * If disabled, a coming soon message will be shown
   */
  pageEnabled?: boolean | null;
  heroEnabled?: boolean | null;
  heroHeading?: string | null;
  heroHeadingFont?: (string | null) | Font;
  heroHeadingColor?: string | null;
  heroSubheading?: string | null;
  heroSubheadingFont?: (string | null) | Font;
  heroSubheadingColor?: string | null;
  featuredVideoEnabled?: boolean | null;
  featuredVideoBadge?: string | null;
  featuredVideoBadgeColor?: string | null;
  featuredVideoBadgeTextColor?: string | null;
  featuredVideoTitle?: string | null;
  featuredVideoTitleFont?: (string | null) | Font;
  featuredVideoTitleColor?: string | null;
  featuredVideoThumbnail?: (string | null) | Media;
  /**
   * Enter YouTube or Vimeo video URL
   */
  featuredVideoUrl?: string | null;
  featuredVideoDuration?: string | null;
  featuredVideoDescription?: string | null;
  playerBorderEnabled?: boolean | null;
  playerBorderColor?: string | null;
  playButtonColor?: string | null;
  categoriesEnabled?: boolean | null;
  categories?:
    | {
        name: string;
        /**
         * Used for filtering (auto-generated if empty)
         */
        slug?: string | null;
        icon?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  categoryPillActiveColor?: string | null;
  categoryPillActiveTextColor?: string | null;
  categoryPillInactiveColor?: string | null;
  categoryPillInactiveTextColor?: string | null;
  galleryEnabled?: boolean | null;
  gallerySectionTitle?: string | null;
  gallerySectionTitleFont?: (string | null) | Font;
  gallerySectionTitleColor?: string | null;
  galleryBorderAccentColor?: string | null;
  galleryColumns?: ('2' | '3' | '4') | null;
  galleryGap?: ('gap-4' | 'gap-6' | 'gap-8') | null;
  /**
   * Add and manage your video/vlog collection
   */
  videos?:
    | {
        title: string;
        slug?: string | null;
        thumbnail?: (string | null) | Media;
        /**
         * Full YouTube or Vimeo URL
         */
        videoUrl?: string | null;
        /**
         * Use this for custom video players or other embed sources
         */
        embedCode?: string | null;
        duration?: string | null;
        /**
         * Must match one of the category slugs
         */
        category?: string | null;
        views?: number | null;
        publishedAt?: string | null;
        description?: string | null;
        tags?: string | null;
        isFeatured?: boolean | null;
        showNewBadge?: boolean | null;
        id?: string | null;
      }[]
    | null;
  videoCardTitleFont?: (string | null) | Font;
  videoCardTitleColor?: string | null;
  videoCardCategoryColor?: string | null;
  videoCardViewsColor?: string | null;
  videoCardPlayButtonColor?: string | null;
  videoCardDurationBgColor?: string | null;
  videoCardDurationTextColor?: string | null;
  subscribeCardEnabled?: boolean | null;
  subscribeCardBackgroundColor?: string | null;
  subscribeCardHeading?: string | null;
  subscribeCardHeadingFont?: (string | null) | Font;
  subscribeCardHeadingColor?: string | null;
  subscribeCardDescription?: string | null;
  subscribeCardDescriptionColor?: string | null;
  subscribeButtonText?: string | null;
  /**
   * YouTube channel, newsletter link, etc.
   */
  subscribeButtonUrl?: string | null;
  subscribeButtonBgColor?: string | null;
  subscribeButtonTextColor?: string | null;
  showYouTubeStats?: boolean | null;
  /**
   * e.g. "125K subscribers"
   */
  youtubeSubscriberCount?: string | null;
  /**
   * e.g. "2.5M views"
   */
  youtubeTotalViews?: string | null;
  mustWatchEnabled?: boolean | null;
  mustWatchBackgroundColor?: string | null;
  mustWatchBorderColor?: string | null;
  mustWatchHeading?: string | null;
  mustWatchHeadingFont?: (string | null) | Font;
  mustWatchHeadingColor?: string | null;
  mustWatchItems?:
    | {
        title: string;
        subtitle?: string | null;
        image?: (string | null) | Media;
        videoUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  mustWatchTitleColor?: string | null;
  mustWatchSubtitleColor?: string | null;
  socialFollowEnabled?: boolean | null;
  socialFollowHeading?: string | null;
  socialFollowHeadingFont?: (string | null) | Font;
  socialFollowHeadingColor?: string | null;
  socialLinks?:
    | {
        platform?: ('youtube' | 'instagram' | 'tiktok' | 'twitter' | 'facebook' | 'pinterest' | 'custom') | null;
        url: string;
        icon?: (string | null) | Media;
        /**
         * e.g. "smart_display", "camera", "share"
         */
        materialIcon?: string | null;
        id?: string | null;
      }[]
    | null;
  socialIconColor?: string | null;
  socialIconHoverColor?: string | null;
  socialSectionBorderColor?: string | null;
  playlistsEnabled?: boolean | null;
  playlistsSectionHeading?: string | null;
  playlistsSectionHeadingFont?: (string | null) | Font;
  playlistsSectionHeadingColor?: string | null;
  playlists?:
    | {
        name: string;
        description?: string | null;
        coverImage?: (string | null) | Media;
        videoCount?: number | null;
        youtubePlaylistUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  playlistCardBgColor?: string | null;
  playlistCardBorderColor?: string | null;
  pageBackgroundColor?: string | null;
  /**
   * Used for buttons, highlights, play buttons
   */
  primaryAccentColor?: string | null;
  /**
   * Used for cards, sidebar sections
   */
  secondaryBackgroundColor?: string | null;
  cardBackgroundColor?: string | null;
  borderColor?: string | null;
  textColor?: string | null;
  mutedTextColor?: string | null;
  showSidebar?: boolean | null;
  sidebarPosition?: ('right' | 'left') | null;
  maxContentWidth?: ('4xl' | '5xl' | '6xl' | '7xl') | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  ogImage?: (string | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  /**
   * Background color for both the top bar and menu overlay
   */
  headerBackgroundColor?: string | null;
  /**
   * Default text color for the header (can be overridden per item)
   */
  headerTextColor?: string | null;
  logo?: (string | null) | Media;
  ownerName?: string | null;
  ownerFont?: (string | null) | Font;
  ownerColor?: string | null;
  navItems?:
    | {
        label: string;
        link: string;
        newTab?: boolean | null;
        font?: (string | null) | Font;
        color?: string | null;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        platform: string;
        url: string;
        icon?: (string | null) | Media;
        font?: (string | null) | Font;
        color?: string | null;
        id?: string | null;
      }[]
    | null;
  navIcons?:
    | {
        /**
         * Uncheck to hide this icon from the header
         */
        enabled?: boolean | null;
        type: 'search' | 'link';
        icon?: (string | null) | Media;
        /**
         * Display this icon
         */
        showIcon?: boolean | null;
        /**
         * Display icon on desktop view
         */
        showIconOnDesktop?: boolean | null;
        /**
         * Display icon on mobile view
         */
        showIconOnMobile?: boolean | null;
        /**
         * Display text label independently
         */
        showLabel?: boolean | null;
        /**
         * Display label on desktop view
         */
        showLabelOnDesktop?: boolean | null;
        /**
         * Display label on mobile view
         */
        showLabelOnMobile?: boolean | null;
        link?: string | null;
        newTab?: boolean | null;
        label?: string | null;
        font?: (string | null) | Font;
        color?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Main accent color (Dusty Rose)
   */
  primaryColor?: string | null;
  /**
   * Secondary accent color (Golden)
   */
  secondaryColor?: string | null;
  /**
   * Page/section background color (Cream)
   */
  backgroundColor?: string | null;
  /**
   * Main text color (Dark Olive)
   */
  textColor?: string | null;
  /**
   * Secondary/muted text color (Muted Olive)
   */
  mutedTextColor?: string | null;
  /**
   * Default border color
   */
  borderColor?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  enabled?: boolean | null;
  brandEnabled?: boolean | null;
  brandName?: string | null;
  brandNameFont?: (string | null) | Font;
  brandNameColor?: string | null;
  brandDescription?: string | null;
  brandDescriptionFont?: (string | null) | Font;
  brandDescriptionColor?: string | null;
  discoverLinksEnabled?: boolean | null;
  discoverLinksHeading?: string | null;
  discoverLinks?:
    | {
        label: string;
        link: string;
        newTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  infoLinksEnabled?: boolean | null;
  infoLinksHeading?: string | null;
  infoLinks?:
    | {
        label: string;
        link: string;
        newTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  newsletterEnabled?: boolean | null;
  newsletterHeading?: string | null;
  newsletterHeadingFont?: (string | null) | Font;
  newsletterHeadingColor?: string | null;
  newsletterDescription?: string | null;
  newsletterDescriptionFont?: (string | null) | Font;
  newsletterDescriptionColor?: string | null;
  newsletterButtonText?: string | null;
  socialLinksEnabled?: boolean | null;
  socialLinks?:
    | {
        platform: string;
        url: string;
        /**
         * If disabled, only the platform name text will be shown
         */
        showIcon?: boolean | null;
        /**
         * Upload a custom icon, or leave empty to use the default icon
         */
        icon?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  copyrightEnabled?: boolean | null;
  copyrightText?: string | null;
  copyrightTextFont?: (string | null) | Font;
  copyrightTextColor?: string | null;
  /**
   * Main accent color (Dusty Rose)
   */
  primaryColor?: string | null;
  /**
   * Secondary accent color (Golden)
   */
  secondaryColor?: string | null;
  /**
   * Footer background color (Cream)
   */
  backgroundColor?: string | null;
  /**
   * Main text color (Dark Olive)
   */
  textColor?: string | null;
  /**
   * Secondary/muted text color (Muted Olive)
   */
  mutedTextColor?: string | null;
  /**
   * Default border color
   */
  borderColor?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "join-our-inner-circle".
 */
export interface JoinOurInnerCircle {
  id: string;
  enabled?: boolean | null;
  title?: string | null;
  titleFont?: (string | null) | Font;
  titleColor?: string | null;
  description?: string | null;
  descriptionFont?: (string | null) | Font;
  descriptionColor?: string | null;
  buttonText?: string | null;
  buttonFont?: (string | null) | Font;
  buttonTextColor?: string | null;
  buttonBackgroundColor?: string | null;
  backgroundColor?: string | null;
  /**
   * Main accent color (Dusty Rose)
   */
  primaryColor?: string | null;
  /**
   * Secondary accent color (Golden)
   */
  secondaryColor?: string | null;
  /**
   * Main text color (Dark Olive)
   */
  textColor?: string | null;
  /**
   * Secondary/muted text color (Muted Olive)
   */
  mutedTextColor?: string | null;
  /**
   * Default border color
   */
  borderColor?: string | null;
  /**
   * Background color for input fields
   */
  inputBackgroundColor?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  pageEnabled?: T;
  heroEnabled?: T;
  showHeroImage?: T;
  heroImage?: T;
  heroHeadingLine1?: T;
  heroHeadingLine1Font?: T;
  heroHeadingLine1Color?: T;
  heroHeadingLine2?: T;
  heroHeadingLine2Font?: T;
  heroHeadingLine2Color?: T;
  heroDescription?: T;
  heroDescriptionFont?: T;
  heroDescriptionColor?: T;
  heroButtonText?: T;
  heroButtonLink?: T;
  heroButtonFont?: T;
  heroButtonTextColor?: T;
  heroButtonBgColor?: T;
  aboutPreviewEnabled?: T;
  showAboutPreviewImage?: T;
  aboutPreviewImage?: T;
  aboutPreviewSectionLabel?: T;
  aboutPreviewSectionLabelFont?: T;
  aboutPreviewSectionLabelColor?: T;
  aboutPreviewHeadingNormal?: T;
  aboutPreviewHeadingNormalFont?: T;
  aboutPreviewHeadingNormalColor?: T;
  aboutPreviewHeadingAccent?: T;
  aboutPreviewHeadingAccentFont?: T;
  aboutPreviewHeadingAccentColor?: T;
  aboutPreviewTextMain?: T;
  aboutPreviewTextMainFont?: T;
  aboutPreviewTextMainColor?: T;
  aboutPreviewTextSecondary?: T;
  aboutPreviewTextSecondaryFont?: T;
  aboutPreviewTextSecondaryColor?: T;
  aboutPreviewButtonText?: T;
  aboutPreviewButtonLink?: T;
  shopPreviewEnabled?: T;
  shopPreviewSectionLabel?: T;
  shopPreviewSectionLabelFont?: T;
  shopPreviewSectionLabelColor?: T;
  shopPreviewHeadingNormal?: T;
  shopPreviewHeadingNormalFont?: T;
  shopPreviewHeadingNormalColor?: T;
  shopPreviewHeadingAccent?: T;
  shopPreviewHeadingAccentFont?: T;
  shopPreviewHeadingAccentColor?: T;
  shopPreviewDescription?: T;
  shopPreviewDescriptionFont?: T;
  shopPreviewDescriptionColor?: T;
  shopPreviewButtonText?: T;
  shopPreviewButtonLink?: T;
  blogPreviewEnabled?: T;
  blogPreviewSectionLabel?: T;
  blogPreviewSectionLabelFont?: T;
  blogPreviewSectionLabelColor?: T;
  blogPreviewHeadingNormal?: T;
  blogPreviewHeadingNormalFont?: T;
  blogPreviewHeadingNormalColor?: T;
  blogPreviewHeadingAccent?: T;
  blogPreviewHeadingAccentFont?: T;
  blogPreviewHeadingAccentColor?: T;
  blogPreviewButtonText?: T;
  blogPreviewButtonLink?: T;
  watchPreviewEnabled?: T;
  watchPreviewSectionLabel?: T;
  watchPreviewSectionLabelFont?: T;
  watchPreviewSectionLabelColor?: T;
  watchPreviewHeadingNormal?: T;
  watchPreviewHeadingNormalFont?: T;
  watchPreviewHeadingNormalColor?: T;
  watchPreviewHeadingAccent?: T;
  watchPreviewHeadingAccentFont?: T;
  watchPreviewHeadingAccentColor?: T;
  watchPreviewDescription?: T;
  watchPreviewDescriptionFont?: T;
  watchPreviewDescriptionColor?: T;
  watchPreviewButtonText?: T;
  watchPreviewButtonLink?: T;
  contactPreviewEnabled?: T;
  contactPreviewSectionLabel?: T;
  contactPreviewSectionLabelFont?: T;
  contactPreviewSectionLabelColor?: T;
  contactPreviewHeadingNormal?: T;
  contactPreviewHeadingNormalFont?: T;
  contactPreviewHeadingNormalColor?: T;
  contactPreviewHeadingAccent?: T;
  contactPreviewHeadingAccentFont?: T;
  contactPreviewHeadingAccentColor?: T;
  contactPreviewDescription?: T;
  contactPreviewDescriptionFont?: T;
  contactPreviewDescriptionColor?: T;
  contactPreviewButtonText?: T;
  contactPreviewButtonLink?: T;
  primaryColor?: T;
  secondaryColor?: T;
  backgroundColor?: T;
  cardBackgroundColor?: T;
  textColor?: T;
  mutedTextColor?: T;
  borderColor?: T;
  buttonPrimaryBgColor?: T;
  buttonPrimaryTextColor?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-page_select".
 */
export interface BlogPageSelect<T extends boolean = true> {
  pageEnabled?: T;
  headerEnabled?: T;
  sectionLabel?: T;
  sectionLabelFont?: T;
  sectionLabelColor?: T;
  headingNormal?: T;
  headingNormalFont?: T;
  headingNormalColor?: T;
  headingAccent?: T;
  headingAccentFont?: T;
  headingAccentColor?: T;
  description?: T;
  descriptionFont?: T;
  descriptionColor?: T;
  newsletterHeading?: T;
  newsletterHeadingFont?: T;
  newsletterHeadingColor?: T;
  newsletterText?: T;
  newsletterTextFont?: T;
  newsletterTextColor?: T;
  newsletterButtonText?: T;
  newsletterButtonTextFont?: T;
  newsletterButtonTextColor?: T;
  shareHeading?: T;
  shareHeadingFont?: T;
  shareHeadingColor?: T;
  shareSubheading?: T;
  shareSubheadingFont?: T;
  shareSubheadingColor?: T;
  socialPlatforms?:
    | T
    | {
        platform?: T;
        shareUrl?: T;
        showIcon?: T;
        icon?: T;
        customText?: T;
        textFont?: T;
        textColor?: T;
        id?: T;
      };
  primaryColor?: T;
  secondaryColor?: T;
  backgroundColor?: T;
  cardBackgroundColor?: T;
  textColor?: T;
  mutedTextColor?: T;
  borderColor?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  pageEnabled?: T;
  heroEnabled?: T;
  showHeroImage?: T;
  heroImage?: T;
  sectionLabel?: T;
  sectionLabelFont?: T;
  sectionLabelColor?: T;
  headingNormal?: T;
  headingNormalFont?: T;
  headingNormalColor?: T;
  headingAccent?: T;
  headingAccentFont?: T;
  headingAccentColor?: T;
  introTextMain?: T;
  introTextMainFont?: T;
  introTextMainColor?: T;
  introTextSecondary?: T;
  introTextSecondaryFont?: T;
  introTextSecondaryColor?: T;
  showSignatureImage?: T;
  signatureImage?: T;
  philosophyEnabled?: T;
  philosophyLabel?: T;
  philosophyLabelFont?: T;
  philosophyLabelColor?: T;
  philosophyQuote?: T;
  philosophyQuoteFont?: T;
  philosophyQuoteColor?: T;
  philosophyText?: T;
  philosophyTextFont?: T;
  philosophyTextColor?: T;
  valuesEnabled?: T;
  valuesLabel?: T;
  valuesLabelFont?: T;
  valuesLabelColor?: T;
  valuesHeadingNormal?: T;
  valuesHeadingNormalFont?: T;
  valuesHeadingNormalColor?: T;
  valuesHeadingAccent?: T;
  valuesHeadingAccentFont?: T;
  valuesHeadingAccentColor?: T;
  values?:
    | T
    | {
        showIcon?: T;
        icon?: T;
        title?: T;
        titleFont?: T;
        titleColor?: T;
        description?: T;
        descriptionFont?: T;
        descriptionColor?: T;
        id?: T;
      };
  primaryColor?: T;
  secondaryColor?: T;
  backgroundColor?: T;
  cardBackgroundColor?: T;
  textColor?: T;
  mutedTextColor?: T;
  borderColor?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop-page_select".
 */
export interface ShopPageSelect<T extends boolean = true> {
  pageEnabled?: T;
  heroEnabled?: T;
  heroBackgroundColor?: T;
  showHeroImage?: T;
  heroImage?: T;
  heroImageOpacity?: T;
  heroSectionLabel?: T;
  heroSectionLabelFont?: T;
  heroSectionLabelColor?: T;
  heroHeading?: T;
  heroHeadingFont?: T;
  heroHeadingColor?: T;
  heroDescription?: T;
  heroDescriptionFont?: T;
  heroDescriptionColor?: T;
  heroPrimaryButtonEnabled?: T;
  heroPrimaryButtonText?: T;
  heroPrimaryButtonLink?: T;
  heroPrimaryButtonFont?: T;
  heroPrimaryButtonBgColor?: T;
  heroPrimaryButtonTextColor?: T;
  heroSecondaryButtonEnabled?: T;
  heroSecondaryButtonText?: T;
  heroSecondaryButtonLink?: T;
  heroSecondaryButtonFont?: T;
  heroSecondaryButtonBorderColor?: T;
  heroSecondaryButtonTextColor?: T;
  filterBarEnabled?: T;
  categories?:
    | T
    | {
        name?: T;
        slug?: T;
        id?: T;
      };
  categoryFont?: T;
  categoryActiveColor?: T;
  categoryInactiveColor?: T;
  showSortDropdown?: T;
  sortOptions?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  productsEnabled?: T;
  productsGridColumns?: T;
  productCardHeight?: T;
  showQuickViewButton?: T;
  quickViewButtonText?: T;
  products?:
    | T
    | {
        name?: T;
        description?: T;
        price?: T;
        salePrice?: T;
        category?: T;
        image?: T;
        badge?: T;
        badgeColor?: T;
        link?: T;
        isDigital?: T;
        publishedAt?: T;
        id?: T;
      };
  productNameFont?: T;
  productNameColor?: T;
  productPriceFont?: T;
  productPriceColor?: T;
  productCategoryColor?: T;
  bannerEnabled?: T;
  bannerBackgroundColor?: T;
  bannerSectionLabel?: T;
  bannerSectionLabelFont?: T;
  bannerSectionLabelColor?: T;
  bannerHeading?: T;
  bannerHeadingFont?: T;
  bannerHeadingColor?: T;
  bannerDescription?: T;
  bannerDescriptionFont?: T;
  bannerDescriptionColor?: T;
  bannerButtonText?: T;
  bannerButtonLink?: T;
  bannerButtonFont?: T;
  bannerButtonBgColor?: T;
  bannerButtonTextColor?: T;
  pageBackgroundColor?: T;
  primaryAccentColor?: T;
  secondaryAccentColor?: T;
  borderColor?: T;
  cardBackgroundColor?: T;
  cardHoverEffect?: T;
  currencySymbol?: T;
  currencyPosition?: T;
  showAddToCartButton?: T;
  addToCartButtonText?: T;
  externalCheckoutEnabled?: T;
  externalCheckoutButtonText?: T;
  showOutOfStock?: T;
  outOfStockText?: T;
  showSaleBadge?: T;
  saleBadgeText?: T;
  saleBadgeColor?: T;
  emptyStateHeading?: T;
  emptyStateDescription?: T;
  emptyStateIcon?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  pageEnabled?: T;
  heroEnabled?: T;
  heroHeading?: T;
  heroHeadingFont?: T;
  heroHeadingColor?: T;
  heroDescription?: T;
  heroDescriptionFont?: T;
  heroDescriptionColor?: T;
  contactMethodsEnabled?: T;
  contactMethodsHeading?: T;
  contactMethodsHeadingFont?: T;
  contactMethodsHeadingColor?: T;
  contactMethodsSubheading?: T;
  contactMethods?:
    | T
    | {
        icon?: T;
        iconMaterialSymbol?: T;
        iconColor?: T;
        title?: T;
        titleFont?: T;
        titleColor?: T;
        description?: T;
        value?: T;
        link?: T;
        id?: T;
      };
  quickResponseEnabled?: T;
  quickResponseIcon?: T;
  quickResponseTitle?: T;
  quickResponseDescription?: T;
  quickResponseBgColor?: T;
  quickResponseTextColor?: T;
  formEnabled?: T;
  formIcon?: T;
  formIconColor?: T;
  formHeading?: T;
  formHeadingFont?: T;
  formHeadingColor?: T;
  formBackgroundColor?: T;
  formBorderColor?: T;
  nameFieldLabel?: T;
  nameFieldPlaceholder?: T;
  emailFieldLabel?: T;
  emailFieldPlaceholder?: T;
  messageFieldLabel?: T;
  messageFieldPlaceholder?: T;
  submitButtonText?: T;
  submitButtonIcon?: T;
  submitButtonBgColor?: T;
  submitButtonTextColor?: T;
  inputBackgroundColor?: T;
  inputBorderColor?: T;
  inputTextColor?: T;
  labelColor?: T;
  servicesEnabled?: T;
  servicesHeading?: T;
  servicesHeadingFont?: T;
  servicesHeadingColor?: T;
  servicesDescription?: T;
  servicesDescriptionFont?: T;
  servicesDescriptionColor?: T;
  services?:
    | T
    | {
        icon?: T;
        iconEmoji?: T;
        title?: T;
        titleFont?: T;
        titleColor?: T;
        description?: T;
        descriptionColor?: T;
        id?: T;
      };
  serviceCardBackgroundColor?: T;
  serviceCardBorderColor?: T;
  faqEnabled?: T;
  faqHeading?: T;
  faqHeadingFont?: T;
  faqHeadingColor?: T;
  faqDescription?: T;
  faqDescriptionFont?: T;
  faqDescriptionColor?: T;
  faqs?:
    | T
    | {
        question?: T;
        questionFont?: T;
        questionColor?: T;
        answer?: T;
        answerColor?: T;
        id?: T;
      };
  faqCardBackgroundColor?: T;
  faqCardBorderColor?: T;
  businessBannerEnabled?: T;
  businessBannerBackgroundColor?: T;
  businessBannerHeading?: T;
  businessBannerHeadingFont?: T;
  businessBannerHeadingColor?: T;
  businessBannerDescription?: T;
  businessBannerDescriptionFont?: T;
  businessBannerDescriptionColor?: T;
  businessBannerNote?: T;
  businessBannerNoteColor?: T;
  pageBackgroundColor?: T;
  primaryAccentColor?: T;
  cardBackgroundColor?: T;
  borderColor?: T;
  textColor?: T;
  mutedTextColor?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "watch-page_select".
 */
export interface WatchPageSelect<T extends boolean = true> {
  pageEnabled?: T;
  heroEnabled?: T;
  heroHeading?: T;
  heroHeadingFont?: T;
  heroHeadingColor?: T;
  heroSubheading?: T;
  heroSubheadingFont?: T;
  heroSubheadingColor?: T;
  featuredVideoEnabled?: T;
  featuredVideoBadge?: T;
  featuredVideoBadgeColor?: T;
  featuredVideoBadgeTextColor?: T;
  featuredVideoTitle?: T;
  featuredVideoTitleFont?: T;
  featuredVideoTitleColor?: T;
  featuredVideoThumbnail?: T;
  featuredVideoUrl?: T;
  featuredVideoDuration?: T;
  featuredVideoDescription?: T;
  playerBorderEnabled?: T;
  playerBorderColor?: T;
  playButtonColor?: T;
  categoriesEnabled?: T;
  categories?:
    | T
    | {
        name?: T;
        slug?: T;
        icon?: T;
        id?: T;
      };
  categoryPillActiveColor?: T;
  categoryPillActiveTextColor?: T;
  categoryPillInactiveColor?: T;
  categoryPillInactiveTextColor?: T;
  galleryEnabled?: T;
  gallerySectionTitle?: T;
  gallerySectionTitleFont?: T;
  gallerySectionTitleColor?: T;
  galleryBorderAccentColor?: T;
  galleryColumns?: T;
  galleryGap?: T;
  videos?:
    | T
    | {
        title?: T;
        slug?: T;
        thumbnail?: T;
        videoUrl?: T;
        embedCode?: T;
        duration?: T;
        category?: T;
        views?: T;
        publishedAt?: T;
        description?: T;
        tags?: T;
        isFeatured?: T;
        showNewBadge?: T;
        id?: T;
      };
  videoCardTitleFont?: T;
  videoCardTitleColor?: T;
  videoCardCategoryColor?: T;
  videoCardViewsColor?: T;
  videoCardPlayButtonColor?: T;
  videoCardDurationBgColor?: T;
  videoCardDurationTextColor?: T;
  subscribeCardEnabled?: T;
  subscribeCardBackgroundColor?: T;
  subscribeCardHeading?: T;
  subscribeCardHeadingFont?: T;
  subscribeCardHeadingColor?: T;
  subscribeCardDescription?: T;
  subscribeCardDescriptionColor?: T;
  subscribeButtonText?: T;
  subscribeButtonUrl?: T;
  subscribeButtonBgColor?: T;
  subscribeButtonTextColor?: T;
  showYouTubeStats?: T;
  youtubeSubscriberCount?: T;
  youtubeTotalViews?: T;
  mustWatchEnabled?: T;
  mustWatchBackgroundColor?: T;
  mustWatchBorderColor?: T;
  mustWatchHeading?: T;
  mustWatchHeadingFont?: T;
  mustWatchHeadingColor?: T;
  mustWatchItems?:
    | T
    | {
        title?: T;
        subtitle?: T;
        image?: T;
        videoUrl?: T;
        id?: T;
      };
  mustWatchTitleColor?: T;
  mustWatchSubtitleColor?: T;
  socialFollowEnabled?: T;
  socialFollowHeading?: T;
  socialFollowHeadingFont?: T;
  socialFollowHeadingColor?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        icon?: T;
        materialIcon?: T;
        id?: T;
      };
  socialIconColor?: T;
  socialIconHoverColor?: T;
  socialSectionBorderColor?: T;
  playlistsEnabled?: T;
  playlistsSectionHeading?: T;
  playlistsSectionHeadingFont?: T;
  playlistsSectionHeadingColor?: T;
  playlists?:
    | T
    | {
        name?: T;
        description?: T;
        coverImage?: T;
        videoCount?: T;
        youtubePlaylistUrl?: T;
        id?: T;
      };
  playlistCardBgColor?: T;
  playlistCardBorderColor?: T;
  pageBackgroundColor?: T;
  primaryAccentColor?: T;
  secondaryBackgroundColor?: T;
  cardBackgroundColor?: T;
  borderColor?: T;
  textColor?: T;
  mutedTextColor?: T;
  showSidebar?: T;
  sidebarPosition?: T;
  maxContentWidth?: T;
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  headerBackgroundColor?: T;
  headerTextColor?: T;
  logo?: T;
  ownerName?: T;
  ownerFont?: T;
  ownerColor?: T;
  navItems?:
    | T
    | {
        label?: T;
        link?: T;
        newTab?: T;
        font?: T;
        color?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        icon?: T;
        font?: T;
        color?: T;
        id?: T;
      };
  navIcons?:
    | T
    | {
        enabled?: T;
        type?: T;
        icon?: T;
        showIcon?: T;
        showIconOnDesktop?: T;
        showIconOnMobile?: T;
        showLabel?: T;
        showLabelOnDesktop?: T;
        showLabelOnMobile?: T;
        link?: T;
        newTab?: T;
        label?: T;
        font?: T;
        color?: T;
        id?: T;
      };
  primaryColor?: T;
  secondaryColor?: T;
  backgroundColor?: T;
  textColor?: T;
  mutedTextColor?: T;
  borderColor?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  enabled?: T;
  brandEnabled?: T;
  brandName?: T;
  brandNameFont?: T;
  brandNameColor?: T;
  brandDescription?: T;
  brandDescriptionFont?: T;
  brandDescriptionColor?: T;
  discoverLinksEnabled?: T;
  discoverLinksHeading?: T;
  discoverLinks?:
    | T
    | {
        label?: T;
        link?: T;
        newTab?: T;
        id?: T;
      };
  infoLinksEnabled?: T;
  infoLinksHeading?: T;
  infoLinks?:
    | T
    | {
        label?: T;
        link?: T;
        newTab?: T;
        id?: T;
      };
  newsletterEnabled?: T;
  newsletterHeading?: T;
  newsletterHeadingFont?: T;
  newsletterHeadingColor?: T;
  newsletterDescription?: T;
  newsletterDescriptionFont?: T;
  newsletterDescriptionColor?: T;
  newsletterButtonText?: T;
  socialLinksEnabled?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        showIcon?: T;
        icon?: T;
        id?: T;
      };
  copyrightEnabled?: T;
  copyrightText?: T;
  copyrightTextFont?: T;
  copyrightTextColor?: T;
  primaryColor?: T;
  secondaryColor?: T;
  backgroundColor?: T;
  textColor?: T;
  mutedTextColor?: T;
  borderColor?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "join-our-inner-circle_select".
 */
export interface JoinOurInnerCircleSelect<T extends boolean = true> {
  enabled?: T;
  title?: T;
  titleFont?: T;
  titleColor?: T;
  description?: T;
  descriptionFont?: T;
  descriptionColor?: T;
  buttonText?: T;
  buttonFont?: T;
  buttonTextColor?: T;
  buttonBackgroundColor?: T;
  backgroundColor?: T;
  primaryColor?: T;
  secondaryColor?: T;
  textColor?: T;
  mutedTextColor?: T;
  borderColor?: T;
  inputBackgroundColor?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}